import type { Locale } from "./profile";

export type Localized<T = string> = Record<Locale, T>;

export type ProjectCategory =
  | "Legal Tech"
  | "Learning"
  | "Commerce"
  | "Automation"
  | "Career"
  | "IoT"
  | "Security"
  | "Portfolio"
  | "Consulting"
  | "Marketing"
  | "Assessment"
  | "Web"
  | "Automotive";

export type ProjectStatus = "Live" | "Public" | "Prototype" | "Private" | "Foundation" | "Early";

export type ProjectSource =
  | "GitHub README"
  | "GitHub metadata"
  | "GitHub (no public README)"
  | "CV";

export type CaseStudy = {
  problem: Localized<string>;
  approach: Localized<string>;
  result?: Localized<string>;
  context?: Localized<string>;
  constraints?: Localized<string>;
  features?: Localized<string[]>;
  challenges?: Localized<string[]>;
  solutions?: Localized<string[]>;
  results?: Localized<string[]>;
  currentStatus?: Localized<string>;
  lessons?: Localized<string>;
};

export type Project = {
  id: string;
  slug: string;
  name: string;
  category: ProjectCategory;
  status: ProjectStatus;
  source: ProjectSource;
  year: string;
  featured: boolean;
  role: Localized<string>;
  description: Localized<string>;
  impact: Localized<string>;
  tech: string[];
  repo?: string;
  live?: string;
  private?: boolean;
  caseStudy?: CaseStudy;
};

export const projects: Project[] = [
  {
    id: "arabic-legal-research-skill",
    slug: "arabic-legal-research-skill",
    name: "Arabic Legal Research Skill Framework",
    category: "Legal Tech",
    status: "Public",
    source: "GitHub README",
    year: "2025-2026",
    featured: true,
    role: {
      en: "Sole author — methodology design, validation engineering, and documentation.",
      ar: "المؤلف الوحيد — تصميم المنهجية وهندسة التحقق والتوثيق.",
    },
    description: {
      en: "A methodology and validation framework that turns informal AI-assisted Arabic legal research into a disciplined, citation-checked, DOCX-ready process for ChatGPT, Claude, and Codex.",
      ar: "منهجية وإطار تحقق يحوّل البحث القانوني العربي المدعوم بالذكاء الاصطناعي من عملية غير منضبطة إلى مسار موثق ومدقق التوثيق وجاهز لإنتاج DOCX، يعمل مع ChatGPT وClaude وCodex.",
    },
    impact: {
      en: "README documents CI on Python 3.11+, 233 passing tests (1 skipped), and 96.12% coverage against a 95% minimum.",
      ar: "يوثق README تكاملاً مستمرًا على Python 3.11+ و233 اختبارًا ناجحًا (تخطي واحد) وتغطية 96.12% مقابل حد أدنى 95%.",
    },
    tech: ["Python", "Ruff", "GitHub Actions", "DOCX", "JSON Schema", "CLI", "Arabic RTL"],
    repo: "https://github.com/Darhous/arabic-legal-research-skill",
    caseStudy: {
      context: {
        en: "AI tools produce fluent Arabic legal writing, but fluency is not the same as academically valid, citable, verifiable research.",
        ar: "تنتج أدوات الذكاء الاصطناعي كتابة قانونية عربية سلسة، لكن السلاسة لا تعني بحثًا قانونيًا صحيحًا أكاديميًا وقابلًا للتوثيق والتحقق.",
      },
      problem: {
        en: "Arabic legal research generated by AI often appears fluent without being structured, sourced, or verifiable, and each session produces inconsistent output.",
        ar: "كثير من البحث القانوني العربي الناتج عن الذكاء الاصطناعي يبدو سلسًا دون أن يكون منظمًا أو موثقًا أو قابلًا للتحقق، وتختلف مخرجات كل جلسة عن الأخرى.",
      },
      constraints: {
        en: "The framework had to work across three different AI access paths (chat prompts, Claude Code, Codex) and a developer CLI, while staying reproducible: identical inputs must yield consistent outputs.",
        ar: "كان على الإطار العمل عبر ثلاثة مسارات وصول مختلفة للذكاء الاصطناعي (محادثة، Claude Code، Codex) بالإضافة إلى واجهة سطر أوامر، مع الحفاظ على قابلية التكرار: نفس المدخلات يجب أن تنتج نفس المخرجات.",
      },
      approach: {
        en: "Build a two-layer system: a Skill layer of instructions and rules that AI models must follow, and a Framework layer of executable validators, JSON schemas, and a DOCX rendering pipeline.",
        ar: "بناء نظام من طبقتين: طبقة Skill من التعليمات والقواعد التي يجب أن تلتزم بها نماذج الذكاء الاصطناعي، وطبقة Framework من أدوات تحقق تنفيذية ومخططات JSON ومسار لإنتاج DOCX.",
      },
      features: {
        en: [
          "Hierarchical structure enforcement (section → chapter → subsection → topic → subtopic).",
          "Citation and source-validation rules that block unverified claims.",
          "Pre-delivery checklists and schema validators.",
          "RTL-correct DOCX generation with structural validation.",
          "A CLI with schema-check, validate, render-docx, validate-docx, and finalize-word commands and defined exit codes.",
        ],
        ar: [
          "فرض هيكل هرمي (باب ← فصل ← مبحث ← موضوع ← فرع).",
          "قواعد توثيق وتحقق من المصادر تمنع الادعاءات غير الموثقة.",
          "قوائم تحقق قبل التسليم ومدققات مخططات.",
          "إنتاج DOCX صحيح الاتجاه RTL مع تحقق هيكلي.",
          "واجهة CLI بأوامر schema-check وvalidate وrender-docx وvalidate-docx وfinalize-word وأكواد خروج محددة.",
        ],
      },
      challenges: {
        en: [
          "Keeping AI models honest about citations without a live legal database to check against.",
          "Making Arabic RTL DOCX output structurally consistent across renderers.",
        ],
        ar: [
          "إبقاء نماذج الذكاء الاصطناعي ملتزمة بالتوثيق الدقيق دون قاعدة بيانات قانونية حية للتحقق منها.",
          "جعل مخرجات DOCX العربية RTL متسقة هيكليًا عبر مختلف المحركات.",
        ],
      },
      solutions: {
        en: [
          "Explicit verification and citation rules enforced through checklists rather than trusting model output directly.",
          "A dedicated structural DOCX validator run after every render before delivery.",
        ],
        ar: [
          "قواعد تحقق وتوثيق صريحة تُفرض عبر قوائم تحقق بدلًا من الثقة المباشرة في مخرجات النموذج.",
          "مدقق هيكلي مخصص لملفات DOCX يعمل بعد كل عملية إنتاج وقبل التسليم.",
        ],
      },
      results: {
        en: [
          "233 passing automated tests across unit, integration, acceptance, and regression suites.",
          "96.12% code coverage, above the project's own 95% minimum gate.",
          "CI enforced on every change via GitHub Actions with Ruff formatting and linting.",
        ],
        ar: [
          "233 اختبارًا آليًا ناجحًا عبر مجموعات الوحدة والتكامل والقبول والانحدار.",
          "تغطية كود 96.12%، أعلى من الحد الأدنى الذي حدده المشروع لنفسه وهو 95%.",
          "تكامل مستمر مفروض على كل تغيير عبر GitHub Actions مع تنسيق وفحص Ruff.",
        ],
      },
      currentStatus: {
        en: "Public and actively maintained, positioned as Ahmed's flagship legal-tech / AI-tooling project.",
        ar: "عام وقيد الصيانة الفعلية، ويمثل المشروع الرائد لأحمد في التقنية القانونية وأدوات الذكاء الاصطناعي.",
      },
      lessons: {
        en: "Legal-domain AI tooling needs enforced structure, not prompting alone — validators and checklists close the gap between fluent output and trustworthy output.",
        ar: "أدوات الذكاء الاصطناعي في المجال القانوني تحتاج إلى هيكل مفروض وليس مجرد صياغة أوامر جيدة — مدققات وقوائم التحقق هي ما يسد الفجوة بين مخرج سلس ومخرج موثوق.",
      },
    },
  },
  {
    id: "darhous-ai-cloud-academy",
    slug: "darhous-ai-cloud-academy",
    name: "Darhous AI Cloud Academy",
    category: "Learning",
    status: "Live",
    source: "GitHub README",
    year: "2025-2026",
    featured: true,
    role: {
      en: "Sole builder — product architecture, bilingual content system, and deployment.",
      ar: "الباني الوحيد — معمارية المنتج ونظام المحتوى ثنائي اللغة والنشر.",
    },
    description: {
      en: "Arabic-first bilingual learning ecosystem covering AI, cloud, automation, digital skills, career development, language assessment, IoT, tools, projects, and certificates.",
      ar: "منظومة تعليمية ثنائية اللغة عربية أولًا للذكاء الاصطناعي، السحابة، الأتمتة، المهارات الرقمية، التطوير المهني، تقييم اللغة، إنترنت الأشياء، الأدوات، المشاريع، والشهادات.",
    },
    impact: {
      en: "Live platform with broad learning scope, PWA support, and RTL-first educational product architecture.",
      ar: "منصة حية ذات نطاق تعليمي واسع، دعم PWA، ومعمارية منتج تعليمي تدعم RTL أولًا.",
    },
    tech: ["Next.js", "TypeScript", "Supabase", "Tailwind CSS", "PWA", "Gemini AI"],
    repo: "https://github.com/Darhous/darhous-ai-cloud-academy",
    live: "https://darhous-ai-cloud-academy.vercel.app",
    caseStudy: {
      context: {
        en: "Arabic-speaking learners often have to piece together AI, cloud, automation, and career-readiness knowledge from disconnected English-first sources.",
        ar: "غالبًا ما يضطر المتعلم الناطق بالعربية لتجميع معرفة الذكاء الاصطناعي والسحابة والأتمتة والجاهزية المهنية من مصادر متفرقة إنجليزية أولًا.",
      },
      problem: {
        en: "Arabic learners need one ecosystem that connects AI, cloud, automation, career growth, exams, language, IoT, and tools instead of scattered courses.",
        ar: "يحتاج المتعلم العربي إلى منظومة واحدة تربط الذكاء الاصطناعي والسحابة والأتمتة والمسار المهني والاختبارات واللغة وإنترنت الأشياء والأدوات بدلًا من دورات متفرقة.",
      },
      approach: {
        en: "Design an Arabic-first bilingual learning platform with structured routes, practical tools, certificates, and a modern Next.js/Supabase architecture, shipped as an installable PWA.",
        ar: "تصميم منصة تعليمية ثنائية اللغة عربية أولًا بمسارات منظمة وأدوات عملية وشهادات ومعمارية Next.js وSupabase حديثة، منشورة كتطبيق ويب قابل للتثبيت PWA.",
      },
      features: {
        en: [
          "Structured multi-track learning paths across AI, cloud, and automation.",
          "Bilingual, RTL-first interface built on Tailwind CSS.",
          "Supabase-backed accounts, progress, and content.",
          "Installable PWA for offline-friendly access.",
          "AI-assisted learning support via the Gemini API.",
        ],
        ar: [
          "مسارات تعليمية متعددة منظمة عبر الذكاء الاصطناعي والسحابة والأتمتة.",
          "واجهة ثنائية اللغة تدعم RTL أولًا مبنية على Tailwind CSS.",
          "حسابات وتقدّم ومحتوى مدعوم بـ Supabase.",
          "تطبيق PWA قابل للتثبيت لوصول أقرب لوضع عدم الاتصال.",
          "دعم تعلم مدعوم بالذكاء الاصطناعي عبر Gemini API.",
        ],
      },
      results: {
        en: [
          "Shipped and reachable at a live production URL, not a local prototype.",
          "Broadest content scope of Ahmed's public learning products, spanning nine subject areas.",
        ],
        ar: [
          "منشور ومتاح على رابط إنتاجي حي وليس نموذجًا محليًا فقط.",
          "أوسع نطاق محتوى بين منتجات أحمد التعليمية العامة، يغطي تسعة مجالات.",
        ],
      },
      currentStatus: {
        en: "Live and publicly deployed on Vercel.",
        ar: "حي ومنشور للعامة على Vercel.",
      },
    },
  },
  {
    id: "shahy-store",
    slug: "shahy-store",
    name: "ShahY Store",
    category: "Commerce",
    status: "Live",
    source: "GitHub README",
    year: "2025-2026",
    featured: true,
    role: {
      en: "Sole developer — storefront, admin panel, database, auth, and deployment.",
      ar: "المطور الوحيد — واجهة المتجر ولوحة الإدارة وقاعدة البيانات والمصادقة والنشر.",
    },
    description: {
      en: "Luxury Egyptian e-commerce store for imported women's accessories, with storefront, admin panel, database, authentication, WhatsApp order flow, and Vercel deployment.",
      ar: "متجر إلكتروني مصري فاخر لإكسسوارات نسائية مستوردة، يضم واجهة متجر ولوحة إدارة وقاعدة بيانات ومصادقة ومسار طلبات عبر واتساب ونشر على Vercel.",
    },
    impact: {
      en: "Production storefront with documented owner and design/development attribution, admin routes, and a live deployment.",
      ar: "واجهة إنتاجية موثقة مع صاحب المتجر ونسبة التصميم والتطوير ومسارات لوحة إدارة ورابط حي.",
    },
    tech: ["Next.js 16", "TypeScript", "Drizzle ORM", "Supabase", "Better Auth", "Vercel"],
    repo: "https://github.com/Darhous/ShahY-Store",
    live: "https://shah-y-store.vercel.app",
    caseStudy: {
      context: {
        en: "A boutique accessories brand needed a real commerce system rather than a static catalog page.",
        ar: "احتاجت علامة إكسسوارات صغيرة إلى نظام تجارة حقيقي بدلًا من صفحة كتالوج ثابتة.",
      },
      problem: {
        en: "A boutique commerce brand needed more than a storefront: catalog control, an order flow, admin workflows, and reliable deployment.",
        ar: "احتاجت علامة تجارة إلكترونية صغيرة إلى ما هو أكثر من واجهة: تحكم في الكتالوج، مسار طلبات، لوحة إدارة، ونشر موثوق.",
      },
      approach: {
        en: "Build a typed Next.js commerce system with database-backed content, authentication, admin routes, and WhatsApp order fulfillment, then extract the reusable parts into a standalone template.",
        ar: "بناء نظام تجارة إلكترونية Next.js مكتوب بالكامل بـ TypeScript، ببيانات من قاعدة، ومصادقة، ومسارات إدارة، وتنفيذ طلبات عبر واتساب، ثم استخراج الأجزاء القابلة لإعادة الاستخدام في قالب مستقل.",
      },
      features: {
        en: [
          "Public storefront with product catalog and detail pages.",
          "Admin panel for catalog and order management.",
          "Better Auth-backed authentication.",
          "Drizzle ORM over Supabase for typed data access.",
          "WhatsApp-based order fulfillment flow.",
        ],
        ar: [
          "واجهة متجر عامة بكتالوج منتجات وصفحات تفاصيل.",
          "لوحة إدارة لإدارة الكتالوج والطلبات.",
          "مصادقة مبنية على Better Auth.",
          "Drizzle ORM فوق Supabase لوصول بيانات مكتوب النوع.",
          "مسار تنفيذ طلبات عبر واتساب.",
        ],
      },
      results: {
        en: [
          "Live production store handling real catalog, admin, and order operations.",
          "Its architecture became the basis for the reusable Store Master Template.",
        ],
        ar: [
          "متجر إنتاجي حي يدير كتالوجًا حقيقيًا وعمليات إدارة وطلبات.",
          "أصبحت معماريته أساس قالب Store Master Template القابل لإعادة الاستخدام.",
        ],
      },
      currentStatus: {
        en: "Live and publicly deployed.",
        ar: "حي ومنشور للعامة.",
      },
    },
  },
  {
    id: "store-master-template",
    slug: "store-master-template",
    name: "Store Master Template",
    category: "Commerce",
    status: "Foundation",
    source: "GitHub README",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Sole author — extracted and generalized from ShahY Store.",
      ar: "المؤلف الوحيد — تم استخراجه وتعميمه من ShahY Store.",
    },
    description: {
      en: "Reusable e-commerce foundation extracted from ShahY Store, including storefront, admin dashboard, database, auth, storage, automation scripts, and operational docs.",
      ar: "أساس تجارة إلكترونية قابل لإعادة الاستخدام مستخرج من ShahY Store، يشمل الواجهة ولوحة الإدارة وقاعدة البيانات والمصادقة والتخزين وسكربتات الأتمتة والوثائق التشغيلية.",
    },
    impact: {
      en: "Turns one production store into a repeatable implementation system for future stores.",
      ar: "يحوّل متجرًا إنتاجيًا واحدًا إلى نظام تنفيذ قابل للتكرار لمتاجر لاحقة.",
    },
    tech: ["Next.js", "Supabase", "Drizzle ORM", "Better Auth", "PowerShell", "Docs"],
    repo: "https://github.com/Darhous/Store-Master-Template",
  },
  {
    id: "darhous-automation-academy",
    slug: "darhous-automation-academy",
    name: "Darhous Automation Academy",
    category: "Automation",
    status: "Public",
    source: "GitHub README",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Sole builder — product, content, and tooling design.",
      ar: "الباني الوحيد — تصميم المنتج والمحتوى والأدوات.",
    },
    description: {
      en: "Arabic standalone automation learning product with learning paths, templates, a workflow builder, labs, a tools hub, dashboard, and admin foundation.",
      ar: "منتج عربي مستقل لتعليم الأتمتة يضم مسارات تعليم وقوالب وباني مسارات عمل ومعامل عملية ومركز أدوات ولوحة تحكم وأساس إدارة.",
    },
    impact: {
      en: "Includes deterministic blueprint generation, ROI tools, complexity estimation, and automation service pathways.",
      ar: "يتضمن توليد مخططات حتمية وأدوات ROI وتقدير تعقيد المسارات ومسارات خدمات الأتمتة.",
    },
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "LocalStorage", "Automation Design"],
    repo: "https://github.com/Darhous/darhous-automation-academy",
  },
  {
    id: "darhous-career-hub",
    slug: "darhous-career-hub",
    name: "Darhous Career Hub — ATS Resume Analyzer",
    category: "Career",
    status: "Prototype",
    source: "GitHub README",
    year: "2025-2026",
    featured: true,
    role: {
      en: "Sole builder — product design, AI integration, and frontend/backend implementation.",
      ar: "الباني الوحيد — تصميم المنتج ودمج الذكاء الاصطناعي وتنفيذ الواجهة والخلفية.",
    },
    description: {
      en: "Career platform prototype centered on an AI-powered ATS resume analyzer, alongside interview preparation, a CV builder, templates, a jobs portal, and a dashboard.",
      ar: "نموذج منصة مهنية يتمحور حول محلل سيرة ذاتية ATS مدعوم بالذكاء الاصطناعي، إلى جانب تدريب المقابلات وصانع CV وقوالب وبوابة وظائف ولوحة تحكم.",
    },
    impact: {
      en: "The README identifies working backend features for CV upload/AI analysis (Gemini) and interview assessment; other areas run on demonstration data.",
      ar: "يوضح README أن الميزات الخلفية العاملة فعليًا تشمل رفع وتحليل السيرة بالذكاء الاصطناعي عبر Gemini وتقييم المقابلات، بينما تعمل أجزاء أخرى ببيانات تجريبية.",
    },
    tech: ["TypeScript", "Gemini AI", "Career Tools", "ATS", "Dashboard"],
    repo: "https://github.com/Darhous/Darhous-career-hub-google",
    caseStudy: {
      context: {
        en: "Job seekers rarely know why an Applicant Tracking System rejects their resume before a human ever reads it.",
        ar: "نادرًا ما يعرف الباحثون عن عمل سبب رفض نظام تتبع المتقدمين (ATS) لسيرتهم الذاتية قبل أن يقرأها إنسان أصلًا.",
      },
      problem: {
        en: "Candidates need a way to check and improve their CV against ATS logic, prepare for interviews, and manage career materials in one place.",
        ar: "يحتاج المتقدمون إلى وسيلة لفحص وتحسين سيرتهم الذاتية أمام منطق ATS، والاستعداد للمقابلات، وإدارة موادهم المهنية في مكان واحد.",
      },
      approach: {
        en: "Build an ATS Analyzer that accepts PDF/TXT resume uploads, matches them programmatically, and surfaces weaknesses through Gemini-powered analysis, alongside a STAR-method interview trainer.",
        ar: "بناء محلل ATS يستقبل رفع السيرة الذاتية بصيغة PDF أو TXT، يطابقها برمجيًا، ويكشف نقاط الضعف عبر تحليل مدعوم بـ Gemini، إلى جانب مدرب مقابلات بأسلوب STAR.",
      },
      features: {
        en: [
          "ATS Analyzer: upload and AI-assisted matching/weakness detection for PDF or TXT resumes.",
          "Interview preparation with STAR-method response crafting and Gemini assessment.",
          "CV builder for structuring resume data (export features marked in-progress).",
          "ATS-compatible resume templates (in preview).",
        ],
        ar: [
          "محلل ATS: رفع السيرة الذاتية بصيغة PDF أو TXT ومطابقتها وتحديد نقاط ضعفها بمساعدة الذكاء الاصطناعي.",
          "تدريب مقابلات بصياغة إجابات بأسلوب STAR وتقييم عبر Gemini.",
          "صانع سيرة ذاتية لهيكلة بيانات السيرة (ميزات التصدير قيد التطوير).",
          "قوالب سيرة ذاتية متوافقة مع ATS (في مرحلة معاينة).",
        ],
      },
      results: {
        en: [
          "Working end-to-end CV upload → AI analysis → weakness report flow.",
          "Functional Gemini-assessed interview evaluation module.",
        ],
        ar: [
          "مسار عامل من طرف إلى طرف: رفع السيرة ← تحليل بالذكاء الاصطناعي ← تقرير نقاط الضعف.",
          "وحدة تقييم مقابلات عاملة بتقييم Gemini.",
        ],
      },
      currentStatus: {
        en: "Prototype: the ATS analyzer and interview evaluator run on real backend logic; remaining sections (jobs portal, some templates) currently use demonstration data.",
        ar: "نموذج أولي: يعمل محلل ATS ومقيّم المقابلات بمنطق خلفي حقيقي، بينما تعمل أقسام أخرى (بوابة الوظائف وبعض القوالب) حاليًا ببيانات تجريبية.",
      },
    },
  },
  {
    id: "darhous-iot-lab",
    slug: "darhous-iot-lab",
    name: "Darhous IoT Lab",
    category: "IoT",
    status: "Public",
    source: "GitHub README",
    year: "2025-2026",
    featured: true,
    role: {
      en: "Sole builder — curriculum design, simulation content, and platform engineering.",
      ar: "الباني الوحيد — تصميم المنهج ومحتوى المحاكاة وهندسة المنصة.",
    },
    description: {
      en: "Arabic-first IoT, Arduino, robotics, and smart-home educational application with lessons, projects, components, code examples, simulations, challenges, and roadmaps.",
      ar: "تطبيق تعليمي عربي لإنترنت الأشياء وArduino والروبوتات والمنزل الذكي، يضم دروسًا ومشاريع ومكونات وأمثلة كود ومحاكيات وتحديات وخرائط طريق.",
    },
    impact: {
      en: "The V2 README documents 18 learning paths, 60+ lessons, 72 projects, 80 components, 80 code examples, and 35 simulator templates.",
      ar: "يوثق README للإصدار V2 وجود 18 مسارًا و60+ درسًا و72 مشروعًا و80 مكونًا و80 مثال كود و35 قالب محاكاة.",
    },
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "Lucide", "Arduino", "IoT"],
    repo: "https://github.com/Darhous/darhous-iot-lab",
    caseStudy: {
      context: {
        en: "Hands-on IoT and electronics education in Arabic is thin compared to English-language resources, and hardware access is a barrier for many learners.",
        ar: "التعليم العملي لإنترنت الأشياء والإلكترونيات باللغة العربية محدود مقارنة بالمصادر الإنجليزية، ويشكل الوصول إلى الأجهزة عائقًا لكثير من المتعلمين.",
      },
      problem: {
        en: "Arabic-speaking learners need a structured path into IoT, Arduino, robotics, and smart-home concepts without requiring physical hardware to start.",
        ar: "يحتاج المتعلم الناطق بالعربية مسارًا منظمًا لتعلم مفاهيم إنترنت الأشياء وArduino والروبوتات والمنزل الذكي دون الحاجة لأجهزة فعلية للبدء.",
      },
      approach: {
        en: "Build a content-heavy Next.js application combining structured learning paths, real code examples, and browser-based simulator templates so learners can practice before touching hardware.",
        ar: "بناء تطبيق Next.js غني بالمحتوى يجمع بين مسارات تعليم منظمة وأمثلة كود حقيقية وقوالب محاكاة تعمل في المتصفح ليتمرن المتعلم قبل التعامل مع الأجهزة الفعلية.",
      },
      features: {
        en: [
          "18 structured learning paths across IoT, Arduino, robotics, and smart-home topics.",
          "60+ lessons paired with 72 hands-on project briefs.",
          "80 documented components and 80 runnable code examples.",
          "35 browser-based simulator templates for hardware-free practice.",
        ],
        ar: [
          "18 مسار تعليم منظم يغطي إنترنت الأشياء وArduino والروبوتات ومواضيع المنزل الذكي.",
          "أكثر من 60 درسًا مرتبطة بـ72 موجز مشروع عملي.",
          "80 مكونًا موثقًا و80 مثال كود قابل للتشغيل.",
          "35 قالب محاكاة يعمل في المتصفح للتدريب دون أجهزة فعلية.",
        ],
      },
      results: {
        en: [
          "Largest structured content volume among Ahmed's public learning products.",
          "Provides a hardware-free on-ramp into IoT for Arabic-speaking beginners.",
        ],
        ar: [
          "أكبر حجم محتوى منظم بين منتجات أحمد التعليمية العامة.",
          "يوفر بوابة تعلم لإنترنت الأشياء دون الحاجة لأجهزة فعلية للمبتدئين الناطقين بالعربية.",
        ],
      },
      currentStatus: {
        en: "Public and content-complete for its documented V2 scope.",
        ar: "عام ومكتمل المحتوى ضمن نطاقه الموثق للإصدار V2.",
      },
    },
  },
  {
    id: "guardian-nexus",
    slug: "guardian-nexus",
    name: "Guardian-Nexus",
    category: "Security",
    status: "Private",
    source: "CV",
    year: "2025-Present",
    featured: true,
    private: true,
    role: {
      en: "System architect within a government security organization (CV-sourced; implementation detail is confidential).",
      ar: "مهندس النظام داخل جهة أمنية حكومية (مصدره السيرة الذاتية؛ تفاصيل التنفيذ سرية).",
    },
    description: {
      en: "AI-integrated HR and Security ERP architecture referenced in the CV, designed for personnel tracking, threat assessment, and resource allocation for 200+ staff.",
      ar: "معمارية ERP للموارد البشرية والأمن مدعومة بالذكاء الاصطناعي ومذكورة في السيرة الذاتية، موجهة لتتبع الأفراد وتقييم التهديدات وتوزيع الموارد لأكثر من 200 فرد.",
    },
    impact: {
      en: "Represents Ahmed's bridge between public security operations, AI workflows, and practical enterprise systems.",
      ar: "يمثل نقطة وصل بين عمليات الأمن العام ومسارات الذكاء الاصطناعي والأنظمة المؤسسية العملية.",
    },
    tech: ["AI Operations", "Security ERP", "Python", "OSINT", "LLMs"],
    caseStudy: {
      context: {
        en: "As Executive Office Manager & Security Liaison, Ahmed identified that personnel tracking, threat assessment, and resource allocation for 200+ staff were running on fragmented, manual processes.",
        ar: "بصفته مدير مكتب تنفيذي ومنسق أمني، لاحظ أحمد أن تتبع الأفراد وتقييم التهديدات وتوزيع الموارد لأكثر من 200 فرد كانت تعمل عبر عمليات يدوية ومجزأة.",
      },
      problem: {
        en: "A government security organization needed a unified, AI-assisted way to coordinate HR and security intelligence for a large staff without exposing sensitive operational data publicly.",
        ar: "احتاجت جهة أمنية حكومية إلى وسيلة موحدة مدعومة بالذكاء الاصطناعي لتنسيق بيانات الموارد البشرية والذكاء الأمني لعدد كبير من الأفراد دون كشف بيانات تشغيلية حساسة للعلن.",
      },
      constraints: {
        en: "Confidential, government-context system: architecture concept and role can be shared, but implementation detail, source code, and operational data must stay private.",
        ar: "نظام في سياق حكومي وسري: يمكن مشاركة مفهوم المعمارية والدور، لكن تفاصيل التنفيذ والكود التشغيلي والبيانات يجب أن تظل خاصة.",
      },
      approach: {
        en: "Architect an ERP concept that combines HR records, security-liaison workflows, Python automation, OSINT monitoring, and LLM-assisted analysis into one coordinated system.",
        ar: "تصميم مفهوم ERP يجمع سجلات الموارد البشرية ومسارات التنسيق الأمني وأتمتة Python ومراقبة OSINT وتحليل مدعوم بنماذج اللغة الكبيرة في نظام واحد منسق.",
      },
      results: {
        en: [
          "Named and referenced directly in Ahmed's CV as an active architecture initiative.",
          "Demonstrates applied AI-operations experience beyond public GitHub projects.",
        ],
        ar: [
          "مذكور بالاسم في السيرة الذاتية لأحمد كمبادرة معمارية نشطة.",
          "يوضح خبرة تطبيقية في عمليات الذكاء الاصطناعي تتجاوز مشاريع GitHub العامة.",
        ],
      },
      currentStatus: {
        en: "Private / CV-sourced. No public repository or demo exists, and none will be fabricated here.",
        ar: "خاص ومصدره السيرة الذاتية. لا يوجد مستودع أو عرض عام، ولن يتم اختلاق أي منهما هنا.",
      },
    },
  },
  {
    id: "almasa-lab-proposal",
    slug: "almasa-lab-proposal",
    name: "Almasa Medical Laboratory — Digital Transformation Proposal",
    category: "Consulting",
    status: "Public",
    source: "GitHub README",
    year: "2026",
    featured: true,
    role: {
      en: "Sole developer — proposal architecture, interactive UI, and decision-tracking system.",
      ar: "المطور الوحيد — معمارية العرض والواجهة التفاعلية ونظام تتبع القرارات.",
    },
    description: {
      en: "An interactive, Arabic/RTL single-page proposal presenting a full digital-transformation vision for a medical laboratory: public website, patient portal, staff application, admin dashboard, and unified backend.",
      ar: "عرض تفاعلي أحادي الصفحة بالعربية واتجاه RTL يقدم رؤية تحول رقمي كاملة لمعمل طبي: موقع عام، بوابة مرضى، تطبيق للموظفين، لوحة إدارة، وخلفية موحدة.",
    },
    impact: {
      en: "Built as a decision log, not a mockup: the lab owner can review, approve, modify, defer, or exclude each proposed section, and every decision is recorded for the implementation phase.",
      ar: "بُني كسجل قرارات وليس نموذجًا شكليًا فقط: يمكن لصاحب المعمل مراجعة أو اعتماد أو تعديل أو تأجيل أو استبعاد كل قسم مقترح، ويُسجَّل كل قرار لمرحلة التنفيذ.",
    },
    tech: ["React 19", "TypeScript", "Vite", "Tailwind CSS v4", "Framer Motion"],
    repo: "https://github.com/Darhous/almasa-lab-proposal",
    caseStudy: {
      context: {
        en: "A medical laboratory client needed to evaluate a large digital-transformation scope (public site, patient portal, staff app, admin dashboard, backend) before committing budget to full implementation.",
        ar: "احتاج عميل معمل طبي إلى تقييم نطاق تحول رقمي واسع (موقع عام، بوابة مرضى، تطبيق موظفين، لوحة إدارة، خلفية) قبل الالتزام بميزانية للتنفيذ الكامل.",
      },
      problem: {
        en: "Presenting a multi-system digital transformation as a static document makes it hard for a non-technical owner to compare, prioritize, or approve pieces independently.",
        ar: "عرض تحول رقمي متعدد الأنظمة كمستند ثابت يجعل من الصعب على مالك غير تقني المقارنة أو ترتيب الأولويات أو اعتماد الأجزاء بشكل مستقل.",
      },
      approach: {
        en: "Build the proposal itself as a working interactive product: every section of the digital-transformation plan is a live, navigable part of the site with an explicit approve/modify/defer/exclude decision captured in local storage, so the artifact becomes an official decision log.",
        ar: "بناء العرض نفسه كمنتج تفاعلي عامل: كل قسم من خطة التحول الرقمي جزء حي وقابل للتصفح من الموقع، مع قرار صريح (اعتماد/تعديل/تأجيل/استبعاد) يُحفظ محليًا، بحيث يتحول العرض نفسه إلى سجل قرارات رسمي.",
      },
      features: {
        en: [
          "Section-by-section proposal covering website, patient portal, staff app, admin dashboard, and backend.",
          "Per-section decision states: approve, modify, defer, or exclude.",
          "No-backend architecture — decisions persist client-side via localStorage.",
          "Arabic-first, fully RTL interface with Framer Motion interaction detail.",
        ],
        ar: [
          "عرض قسمًا بقسم يغطي الموقع وبوابة المرضى وتطبيق الموظفين ولوحة الإدارة والخلفية.",
          "حالات قرار لكل قسم: اعتماد، تعديل، تأجيل، أو استبعاد.",
          "معمارية بلا خلفية خادم — تُحفظ القرارات في المتصفح عبر localStorage.",
          "واجهة عربية أولًا بالكامل RTL مع تفاصيل تفاعل مبنية على Framer Motion.",
        ],
      },
      results: {
        en: [
          "Turned a sales/consulting document into a functioning, deployable product built with the same stack used for production client work.",
          "Automated GitHub Pages deployment via its own GitHub Actions workflow.",
        ],
        ar: [
          "حوّل مستند مبيعات/استشارة إلى منتج عامل وقابل للنشر مبني بنفس التقنيات المستخدمة في أعمال العملاء الإنتاجية.",
          "نشر آلي على GitHub Pages عبر GitHub Actions الخاص به.",
        ],
      },
      currentStatus: {
        en: "Public and deployed as a proposal/decision-tracking tool; not the final implemented lab system.",
        ar: "عام ومنشور كأداة عرض وتتبع قرارات؛ وليس نظام المعمل النهائي المنفذ.",
      },
    },
  },
  {
    id: "shemo-studio",
    slug: "shemo-studio",
    name: "Shemo Studio",
    category: "Web",
    status: "Public",
    source: "GitHub README",
    year: "2024-2025",
    featured: false,
    role: {
      en: "Sole developer — custom WordPress theme and plugin engineering.",
      ar: "المطور الوحيد — هندسة قالب وإضافة ووردبريس مخصصين.",
    },
    description: {
      en: "A custom WordPress build for a studio brand, including a bespoke plugin (shemo-core), a child theme (shemo-child), and integration documentation.",
      ar: "بناء ووردبريس مخصص لعلامة استوديو، يضم إضافة مخصصة (shemo-core)، وقالبًا فرعيًا (shemo-child)، ووثائق تكامل.",
    },
    impact: {
      en: "35 commits of iterative theme/plugin work; no public description or live URL is currently published for this repository.",
      ar: "35 عملية إيداع (commit) من العمل التكراري على القالب والإضافة؛ لا يوجد وصف عام أو رابط حي منشور حاليًا لهذا المستودع.",
    },
    tech: ["PHP", "WordPress", "JavaScript", "HTML", "CSS"],
    repo: "https://github.com/Darhous/Shemo-Studio",
  },
  {
    id: "darhous-assessment",
    slug: "darhous-assessment",
    name: "Darhous Assessment Platform",
    category: "Assessment",
    status: "Live",
    source: "GitHub metadata",
    year: "2025",
    featured: false,
    role: {
      en: "Sole developer — full-stack build and deployment.",
      ar: "المطور الوحيد — بناء متكامل ونشر.",
    },
    description: {
      en: "A full-stack assessment application with separate frontend and backend, deployed live on Vercel.",
      ar: "تطبيق تقييم متكامل بواجهة أمامية وخلفية منفصلتين، منشور حيًا على Vercel.",
    },
    impact: {
      en: "GitHub metadata shows 30 commits and a working production deployment; no public README describes the assessment domain in detail.",
      ar: "تُظهر بيانات GitHub 30 عملية إيداع ونشرًا إنتاجيًا عاملًا؛ لا يوجد README عام يصف مجال التقييم بالتفصيل.",
    },
    tech: ["JavaScript", "Python", "CSS"],
    repo: "https://github.com/Darhous/darhous-assessment",
    live: "https://darhous-assessment.vercel.app",
  },
  {
    id: "exams-platform",
    slug: "exams-platform",
    name: "Exams Platform",
    category: "Assessment",
    status: "Public",
    source: "GitHub metadata",
    year: "2025",
    featured: false,
    role: {
      en: "Sole developer.",
      ar: "المطور الوحيد.",
    },
    description: {
      en: "A Python exam-administration and grading system with AI-assisted feedback, certificate generation, and Telegram/WhatsApp notification integrations.",
      ar: "نظام إدارة وتصحيح امتحانات مبني بـ Python مع ملاحظات مدعومة بالذكاء الاصطناعي، وإصدار شهادات، وتكامل إشعارات عبر تيليجرام وواتساب.",
    },
    impact: {
      en: "Repository structure shows Gemini-based feedback generation and multi-channel notifications; no public README documents adoption or scale.",
      ar: "يُظهر هيكل المستودع توليد ملاحظات مبني على Gemini وإشعارات متعددة القنوات؛ لا يوجد README عام يوثق حجم الاستخدام أو الانتشار.",
    },
    tech: ["Python", "Gemini AI", "Telegram API", "WhatsApp"],
    repo: "https://github.com/Darhous/Exams_Platform",
  },
  {
    id: "darhous-marketing-social-hub",
    slug: "darhous-marketing-social-hub",
    name: "Darhous Marketing & Social Hub",
    category: "Marketing",
    status: "Prototype",
    source: "GitHub README",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Sole builder — design system, information architecture, and frontend.",
      ar: "الباني الوحيد — نظام التصميم ومعمارية المعلومات والواجهة الأمامية.",
    },
    description: {
      en: "An Arabic-first marketing and social-media portal for digital professionals and agencies, covering content calendars, campaign planning, persona development, and post generation.",
      ar: "بوابة تسويق ووسائل تواصل اجتماعي عربية أولًا للمحترفين والوكالات الرقمية، تغطي تقاويم المحتوى وتخطيط الحملات وبناء الشخصيات التسويقية وتوليد المنشورات.",
    },
    impact: {
      en: "README describes a production-ready Next.js portal on a custom RTL design system with IBM Plex Sans Arabic typography.",
      ar: "يصف README بوابة Next.js جاهزة للإنتاج مبنية على نظام تصميم RTL مخصص بخط IBM Plex Sans Arabic.",
    },
    tech: ["Next.js", "TypeScript", "RTL Design System", "Tailwind CSS"],
    repo: "https://github.com/Darhous/darhous-marketing-social-hub",
  },
  {
    id: "whatsapp-auto-poster",
    slug: "whatsapp-auto-poster",
    name: "WhatsApp Auto-Poster",
    category: "Automation",
    status: "Public",
    source: "GitHub (no public README)",
    year: "2025",
    featured: false,
    role: {
      en: "Sole author.",
      ar: "المؤلف الوحيد.",
    },
    description: {
      en: "A small Python automation utility that posts messages to WhatsApp on a schedule via a GitHub Actions workflow.",
      ar: "أداة أتمتة صغيرة بلغة Python لنشر رسائل على واتساب وفق جدول زمني عبر GitHub Actions.",
    },
    impact: {
      en: "A focused, single-purpose automation script rather than a full product — representative of Ahmed's Python automation habit.",
      ar: "سكربت أتمتة مركّز أحادي الغرض وليس منتجًا كاملاً — يعكس عادة أحمد في أتمتة المهام بـ Python.",
    },
    tech: ["Python", "GitHub Actions", "WhatsApp"],
    repo: "https://github.com/Darhous/whatsapp-auto-poster",
  },
  {
    id: "elfady",
    slug: "elfady",
    name: "Elfady Car Trading",
    category: "Automotive",
    status: "Early",
    source: "GitHub (no public README)",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Owner-listed repository; no public implementation to describe yet.",
      ar: "مستودع مسجل باسم أحمد؛ لا يوجد تنفيذ عام لوصفه بعد.",
    },
    description: {
      en: "A repository reserved under Ahmed's GitHub account for a car-trading/dealership project. The repository is currently public but empty, so no verified feature set, screenshots, or live link can be shown yet.",
      ar: "مستودع محجوز في حساب أحمد على GitHub لمشروع تجارة/معرض سيارات. المستودع عام حاليًا لكنه فارغ، لذلك لا يمكن عرض مزايا أو لقطات شاشة أو رابط حي موثق بعد.",
    },
    impact: {
      en: "Listed here for transparency, not as a completed case study — this entry will be expanded once real code or content is published.",
      ar: "مُدرَج هنا للشفافية وليس كدراسة حالة مكتملة — سيتم توسيع هذا العنصر عند نشر كود أو محتوى حقيقي.",
    },
    tech: [],
    repo: "https://github.com/Darhous/elfady",
  },
  {
    id: "portfolio",
    slug: "ahmed-darhous-portfolio",
    name: "Ahmed Darhous Portfolio",
    category: "Portfolio",
    status: "Live",
    source: "GitHub metadata",
    year: "2026",
    featured: false,
    role: {
      en: "Sole designer and developer.",
      ar: "المصمم والمطور الوحيد.",
    },
    description: {
      en: "This bilingual portfolio itself: a GitHub Pages-compatible Vite + React application with centralized identity, a real project archive, and case-study pages.",
      ar: "هذا البورتفوليو الثنائي اللغة نفسه: تطبيق Vite وReact متوافق مع GitHub Pages بهوية مركزية وأرشيف مشاريع حقيقي وصفحات دراسات حالة.",
    },
    impact: {
      en: "Acts as the public identity system tying together security, legal research, AI operations, and software products.",
      ar: "يمثل نظام الهوية العام الذي يربط الأمن والبحث القانوني وعمليات الذكاء الاصطناعي والمنتجات البرمجية.",
    },
    tech: ["Vite", "React", "TypeScript", "React Router", "GitHub Pages"],
    repo: "https://github.com/Darhous/portofolio",
    live: "https://darhous.github.io/portofolio/",
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((project) => project.slug === slug);
}

export const featuredProjects = projects.filter((project) => project.featured);

export const projectCategories = Array.from(new Set(projects.map((project) => project.category)));
