import type { Locale } from "./profile";

export type Localized<T = string> = Record<Locale, T>;

export type ProjectCategory =
  | "Legal Tech"
  | "Learning"
  | "Commerce"
  | "Automation"
  | "Career"
  | "IoT"
  | "Security"
  | "Portfolio"
  | "Consulting"
  | "Marketing"
  | "Assessment"
  | "Web"
  | "Automotive"
  | "AI Tools"
  | "Data"
  | "Hospitality"
  | "Mobile";

export type ProjectStatus = "Live" | "Public" | "Prototype" | "Private" | "Foundation" | "Early";

export type ProjectSource =
  | "GitHub README"
  | "GitHub metadata"
  | "GitHub (no public README)"
  | "Owner-provided"
  | "CV";

export type CaseStudy = {
  problem: Localized<string>;
  approach: Localized<string>;
  result?: Localized<string>;
  context?: Localized<string>;
  constraints?: Localized<string>;
  features?: Localized<string[]>;
  challenges?: Localized<string[]>;
  solutions?: Localized<string[]>;
  results?: Localized<string[]>;
  currentStatus?: Localized<string>;
  lessons?: Localized<string>;
};

export type ProjectStat = {
  value: string;
  label: Localized<string>;
};

export type Project = {
  id: string;
  slug: string;
  name: string;
  category: ProjectCategory;
  status: ProjectStatus;
  source: ProjectSource;
  year: string;
  featured: boolean;
  role: Localized<string>;
  description: Localized<string>;
  impact: Localized<string>;
  tech: string[];
  repo?: string;
  live?: string;
  private?: boolean;
  caseStudy?: CaseStudy;
  /** Sourced, numeric highlights pulled verbatim from the project's own README/impact copy — never invented. */
  stats?: ProjectStat[];
};

export const projects: Project[] = [
  {
    id: "arabic-legal-research-skill",
    slug: "arabic-legal-research-skill",
    name: "Arabic Legal Research Skill Framework",
    category: "Legal Tech",
    status: "Public",
    source: "GitHub README",
    year: "2025-2026",
    featured: true,
    role: {
      en: "Sole author — methodology design, validation engineering, and documentation.",
      ar: "المؤلف الوحيد — تصميم المنهجية وهندسة التحقق والتوثيق.",
    },
    description: {
      en: "A methodology and validation framework that turns informal AI-assisted Arabic legal research into a disciplined, citation-checked, DOCX-ready process for ChatGPT, Claude, and Codex.",
      ar: "منهجية وإطار تحقق يحوّل البحث القانوني العربي المدعوم بالذكاء الاصطناعي من عملية غير منضبطة إلى مسار موثق ومدقق التوثيق وجاهز لإنتاج DOCX، يعمل مع ChatGPT وClaude وCodex.",
    },
    impact: {
      en: "README documents CI on Python 3.11+, 233 passing tests (1 skipped), and 96.12% coverage against a 95% minimum.",
      ar: "يوثق README تكاملاً مستمرًا على Python 3.11+ و233 اختبارًا ناجحًا (تخطي واحد) وتغطية 96.12% مقابل حد أدنى 95%.",
    },
    tech: ["Python", "Ruff", "GitHub Actions", "DOCX", "JSON Schema", "CLI", "Arabic RTL"],
    repo: "https://github.com/Darhous/arabic-legal-research-skill",
    stats: [
      { value: "233", label: { en: "passing tests", ar: "اختبار ناجح" } },
      { value: "96.12%", label: { en: "code coverage", ar: "تغطية الكود" } },
      { value: "95%", label: { en: "minimum gate", ar: "الحد الأدنى المطلوب" } },
    ],
    caseStudy: {
      context: {
        en: "AI tools produce fluent Arabic legal writing, but fluency is not the same as academically valid, citable, verifiable research.",
        ar: "تنتج أدوات الذكاء الاصطناعي كتابة قانونية عربية سلسة، لكن السلاسة لا تعني بحثًا قانونيًا صحيحًا أكاديميًا وقابلًا للتوثيق والتحقق.",
      },
      problem: {
        en: "Arabic legal research generated by AI often appears fluent without being structured, sourced, or verifiable, and each session produces inconsistent output.",
        ar: "كثير من البحث القانوني العربي الناتج عن الذكاء الاصطناعي يبدو سلسًا دون أن يكون منظمًا أو موثقًا أو قابلًا للتحقق، وتختلف مخرجات كل جلسة عن الأخرى.",
      },
      constraints: {
        en: "The framework had to work across three different AI access paths (chat prompts, Claude Code, Codex) and a developer CLI, while staying reproducible: identical inputs must yield consistent outputs.",
        ar: "كان على الإطار العمل عبر ثلاثة مسارات وصول مختلفة للذكاء الاصطناعي (محادثة، Claude Code، Codex) بالإضافة إلى واجهة سطر أوامر، مع الحفاظ على قابلية التكرار: نفس المدخلات يجب أن تنتج نفس المخرجات.",
      },
      approach: {
        en: "Build a two-layer system: a Skill layer of instructions and rules that AI models must follow, and a Framework layer of executable validators, JSON schemas, and a DOCX rendering pipeline.",
        ar: "بناء نظام من طبقتين: طبقة Skill من التعليمات والقواعد التي يجب أن تلتزم بها نماذج الذكاء الاصطناعي، وطبقة Framework من أدوات تحقق تنفيذية ومخططات JSON ومسار لإنتاج DOCX.",
      },
      features: {
        en: [
          "Hierarchical structure enforcement (section → chapter → subsection → topic → subtopic).",
          "Citation and source-validation rules that block unverified claims.",
          "Pre-delivery checklists and schema validators.",
          "RTL-correct DOCX generation with structural validation.",
          "A CLI with schema-check, validate, render-docx, validate-docx, and finalize-word commands and defined exit codes.",
        ],
        ar: [
          "فرض هيكل هرمي (باب ← فصل ← مبحث ← موضوع ← فرع).",
          "قواعد توثيق وتحقق من المصادر تمنع الادعاءات غير الموثقة.",
          "قوائم تحقق قبل التسليم ومدققات مخططات.",
          "إنتاج DOCX صحيح الاتجاه RTL مع تحقق هيكلي.",
          "واجهة CLI بأوامر schema-check وvalidate وrender-docx وvalidate-docx وfinalize-word وأكواد خروج محددة.",
        ],
      },
      challenges: {
        en: [
          "Keeping AI models honest about citations without a live legal database to check against.",
          "Making Arabic RTL DOCX output structurally consistent across renderers.",
        ],
        ar: [
          "إبقاء نماذج الذكاء الاصطناعي ملتزمة بالتوثيق الدقيق دون قاعدة بيانات قانونية حية للتحقق منها.",
          "جعل مخرجات DOCX العربية RTL متسقة هيكليًا عبر مختلف المحركات.",
        ],
      },
      solutions: {
        en: [
          "Explicit verification and citation rules enforced through checklists rather than trusting model output directly.",
          "A dedicated structural DOCX validator run after every render before delivery.",
        ],
        ar: [
          "قواعد تحقق وتوثيق صريحة تُفرض عبر قوائم تحقق بدلًا من الثقة المباشرة في مخرجات النموذج.",
          "مدقق هيكلي مخصص لملفات DOCX يعمل بعد كل عملية إنتاج وقبل التسليم.",
        ],
      },
      results: {
        en: [
          "233 passing automated tests across unit, integration, acceptance, and regression suites.",
          "96.12% code coverage, above the project's own 95% minimum gate.",
          "CI enforced on every change via GitHub Actions with Ruff formatting and linting.",
        ],
        ar: [
          "233 اختبارًا آليًا ناجحًا عبر مجموعات الوحدة والتكامل والقبول والانحدار.",
          "تغطية كود 96.12%، أعلى من الحد الأدنى الذي حدده المشروع لنفسه وهو 95%.",
          "تكامل مستمر مفروض على كل تغيير عبر GitHub Actions مع تنسيق وفحص Ruff.",
        ],
      },
      currentStatus: {
        en: "Public and actively maintained, positioned as Ahmed's flagship legal-tech / AI-tooling project.",
        ar: "عام وقيد الصيانة الفعلية، ويمثل المشروع الرائد لأحمد في التقنية القانونية وأدوات الذكاء الاصطناعي.",
      },
      lessons: {
        en: "Legal-domain AI tooling needs enforced structure, not prompting alone — validators and checklists close the gap between fluent output and trustworthy output.",
        ar: "أدوات الذكاء الاصطناعي في المجال القانوني تحتاج إلى هيكل مفروض وليس مجرد صياغة أوامر جيدة — مدققات وقوائم التحقق هي ما يسد الفجوة بين مخرج سلس ومخرج موثوق.",
      },
    },
  },
  {
    id: "nexalearn",
    slug: "darhous-ai-cloud-academy",
    name: "NexaLearn by Ahmed Darhous",
    category: "Learning",
    status: "Live",
    source: "GitHub README",
    year: "2025-2026",
    featured: true,
    role: {
      en: "Sole builder — product architecture, all seven learning portals, the AI Studio tool suite, bilingual content system, and deployment.",
      ar: "الباني الوحيد — معمارية المنتج، البوابات السبع التعليمية، مجموعة أدوات AI Studio، نظام المحتوى ثنائي اللغة، والنشر.",
    },
    description: {
      en: "Arabic-first bilingual learning ecosystem unifying seven learning portals (AI Academy, Language Assessment, Digital Exams, Career Hub, Automation Academy, IoT Lab, Nano Banana Prompt Lab) with a suite of AI Studio tools, courses, certificates, and an admin CMS — all in one platform.",
      ar: "منظومة تعليمية ثنائية اللغة عربية أولًا توحّد سبع بوابات تعليمية (أكاديمية الذكاء الاصطناعي، تقييم اللغة، الاختبارات الرقمية، مركز التوظيف، أكاديمية الأتمتة، معمل إنترنت الأشياء، معمل نانو بانانا) مع مجموعة أدوات AI Studio ودورات وشهادات ولوحة إدارة CMS، كل ذلك في منصة واحدة.",
    },
    impact: {
      en: "README documents 325+ commits, 144+ releases, a Next.js 16 / React 19 / Supabase architecture with row-level security, and 8 dedicated AI Studio tools beyond the six learning portals.",
      ar: "يوثق README أكثر من 325 عملية إيداع و144 إصدارًا، ومعمارية Next.js 16 / React 19 / Supabase مع أمان على مستوى الصفوف، و8 أدوات مخصصة ضمن AI Studio بالإضافة إلى ست بوابات تعليمية.",
    },
    tech: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Tailwind CSS 4",
      "Supabase",
      "Framer Motion",
      "Fuse.js",
      "Recharts",
      "React PDF",
      "Resend",
      "Vercel",
    ],
    repo: "https://github.com/Darhous/darhous-ai-cloud-academy",
    live: "https://darhous-ai-cloud-academy.vercel.app",
    stats: [
      { value: "325+", label: { en: "commits", ar: "عملية إيداع" } },
      { value: "144+", label: { en: "releases", ar: "إصدار" } },
      { value: "7", label: { en: "learning portals", ar: "بوابة تعليمية" } },
      { value: "8", label: { en: "AI Studio tools", ar: "أداة AI Studio" } },
    ],
    caseStudy: {
      context: {
        en: "Arabic-speaking learners often have to piece together AI, cloud, automation, and career-readiness knowledge from disconnected English-first sources, each with its own account, certificate format, and design language.",
        ar: "غالبًا ما يضطر المتعلم الناطق بالعربية لتجميع معرفة الذكاء الاصطناعي والسحابة والأتمتة والجاهزية المهنية من مصادر متفرقة إنجليزية أولًا، لكل منها حساب وصيغة شهادة ولغة تصميم مختلفة.",
      },
      problem: {
        en: "Arabic learners need one ecosystem that connects AI education, language assessment, digital-skills exams, career tools, automation training, and IoT learning instead of scattered, disconnected courses.",
        ar: "يحتاج المتعلم العربي إلى منظومة واحدة تربط تعليم الذكاء الاصطناعي وتقييم اللغة واختبارات المهارات الرقمية وأدوات التوظيف وتدريب الأتمتة وتعلم إنترنت الأشياء بدلًا من دورات متفرقة ومنفصلة.",
      },
      approach: {
        en: "Design a single Next.js/Supabase platform with seven purpose-built portals sharing one account system, one certificate system, and one design language, then extend it with a standalone 'AI Studio' — a suite of focused AI tools (mentor, prompt tools, recommenders, generators) that support learners across every portal.",
        ar: "تصميم منصة واحدة على Next.js وSupabase تضم سبع بوابات مخصصة تشترك في نظام حساب واحد ونظام شهادات واحد ولغة تصميم واحدة، ثم توسيعها بـ'AI Studio' المستقل — مجموعة أدوات ذكاء اصطناعي مركزة (مرشد، أدوات برومبت، أنظمة توصية، مولدات) تدعم المتعلم عبر كل بوابة.",
      },
      features: {
        en: [
          "Seven learning portals: AI Academy, Language Assessment, Digital Exams, Career Hub, Automation Academy, IoT/Arduino Lab, and Nano Banana Prompt Lab — each documented as an independent project in this archive.",
          "AI Studio tool suite (8 tools): AI Mentor, Prompt Studio, Prompt Score, Prompt Battle, Claude Code Prompt Generator, AI Tool Recommender, Learning Roadmap Generator, and AI Project Generator.",
          "Platform-wide systems: courses with MDX lessons, a tools directory, a prompt library, a technical glossary, Fuse.js-powered smart search, a leaderboard/achievement system, and a certificate system with public QR verification pages.",
          "Supabase-backed CMS/admin dashboard with draft/publish workflows and row-level security, plus static fallback rendering for production resilience.",
        ],
        ar: [
          "سبع بوابات تعليمية: أكاديمية الذكاء الاصطناعي، تقييم اللغة، الاختبارات الرقمية، مركز التوظيف، أكاديمية الأتمتة، معمل إنترنت الأشياء/Arduino، ومعمل نانو بانانا — كل واحدة موثقة كمشروع مستقل في هذا الأرشيف.",
          "مجموعة أدوات AI Studio (8 أدوات): AI Mentor، Prompt Studio، Prompt Score، Prompt Battle، مولد أوامر Claude Code، مرشّح أدوات الذكاء الاصطناعي، مولد خرائط التعلم، ومولد المشاريع بالذكاء الاصطناعي.",
          "أنظمة على مستوى المنصة: دورات بدروس MDX، دليل أدوات، مكتبة برومبتات، قاموس تقني، بحث ذكي مدعوم بـ Fuse.js، نظام ترتيب وإنجازات، ونظام شهادات مع صفحات تحقق عامة عبر QR.",
          "لوحة إدارة/CMS مبنية على Supabase بمسارات مسودة/نشر وأمان على مستوى الصفوف، مع عرض احتياطي ثابت لمرونة الإنتاج.",
        ],
      },
      results: {
        en: [
          "325+ commits and 144+ releases on the main branch — the largest and most actively maintained product in Ahmed's portfolio.",
          "Seven live learning portals plus eight AI tools shipped from a single shared codebase and design system.",
          "A reusable certificate + verification system (React PDF, QR codes, public verification pages) used across every portal.",
        ],
        ar: [
          "أكثر من 325 عملية إيداع و144 إصدارًا على الفرع الرئيسي — أكبر منتجات أحمد وأكثرها صيانة نشطة.",
          "سبع بوابات تعليمية حية بالإضافة إلى ثماني أدوات ذكاء اصطناعي، جميعها من قاعدة كود ونظام تصميم مشترك واحد.",
          "نظام شهادات وتحقق قابل لإعادة الاستخدام (React PDF، رموز QR، صفحات تحقق عامة) مستخدم عبر كل بوابة.",
        ],
      },
      currentStatus: {
        en: "Live and publicly deployed on Vercel. Content management is a hybrid of database-backed and static-fallback rendering, per the README's own migration notes.",
        ar: "حي ومنشور للعامة على Vercel. إدارة المحتوى مزيج من عرض مدعوم بقاعدة بيانات وعرض احتياطي ثابت، وفق ملاحظات الترحيل الموثقة في README نفسه.",
      },
      lessons: {
        en: "A shared account/design/certificate system across seven portals is far more valuable than seven separate products — the AI Studio tools in particular exist because they were cheap to add once the platform's foundations were already shared.",
        ar: "نظام حساب/تصميم/شهادات مشترك عبر سبع بوابات أقيَم بكثير من سبعة منتجات منفصلة — أدوات AI Studio على وجه الخصوص وُجدت لأن إضافتها كانت رخيصة بعد أن أصبحت أسس المنصة مشتركة بالفعل.",
      },
    },
  },
  {
    id: "shahy-store",
    slug: "shahy-store",
    name: "ShahY Store",
    category: "Commerce",
    status: "Live",
    source: "GitHub README",
    year: "2025-2026",
    featured: true,
    role: {
      en: "Sole developer — storefront, admin panel, database, auth, and deployment.",
      ar: "المطور الوحيد — واجهة المتجر ولوحة الإدارة وقاعدة البيانات والمصادقة والنشر.",
    },
    description: {
      en: "Luxury Egyptian e-commerce store for imported women's accessories, with storefront, admin panel, database, authentication, WhatsApp order flow, and Vercel deployment.",
      ar: "متجر إلكتروني مصري فاخر لإكسسوارات نسائية مستوردة، يضم واجهة متجر ولوحة إدارة وقاعدة بيانات ومصادقة ومسار طلبات عبر واتساب ونشر على Vercel.",
    },
    impact: {
      en: "Production storefront with documented owner and design/development attribution, admin routes, and a live deployment.",
      ar: "واجهة إنتاجية موثقة مع صاحب المتجر ونسبة التصميم والتطوير ومسارات لوحة إدارة ورابط حي.",
    },
    tech: ["Next.js 16", "TypeScript", "Drizzle ORM", "Supabase", "Better Auth", "Vercel"],
    repo: "https://github.com/Darhous/ShahY-Store",
    live: "https://shah-y-store.vercel.app",
    caseStudy: {
      context: {
        en: "A boutique accessories brand needed a real commerce system rather than a static catalog page.",
        ar: "احتاجت علامة إكسسوارات صغيرة إلى نظام تجارة حقيقي بدلًا من صفحة كتالوج ثابتة.",
      },
      problem: {
        en: "A boutique commerce brand needed more than a storefront: catalog control, an order flow, admin workflows, and reliable deployment.",
        ar: "احتاجت علامة تجارة إلكترونية صغيرة إلى ما هو أكثر من واجهة: تحكم في الكتالوج، مسار طلبات، لوحة إدارة، ونشر موثوق.",
      },
      approach: {
        en: "Build a typed Next.js commerce system with database-backed content, authentication, admin routes, and WhatsApp order fulfillment, then extract the reusable parts into a standalone template.",
        ar: "بناء نظام تجارة إلكترونية Next.js مكتوب بالكامل بـ TypeScript، ببيانات من قاعدة، ومصادقة، ومسارات إدارة، وتنفيذ طلبات عبر واتساب، ثم استخراج الأجزاء القابلة لإعادة الاستخدام في قالب مستقل.",
      },
      features: {
        en: [
          "Public storefront with product catalog and detail pages.",
          "Admin panel for catalog and order management.",
          "Better Auth-backed authentication.",
          "Drizzle ORM over Supabase for typed data access.",
          "WhatsApp-based order fulfillment flow.",
        ],
        ar: [
          "واجهة متجر عامة بكتالوج منتجات وصفحات تفاصيل.",
          "لوحة إدارة لإدارة الكتالوج والطلبات.",
          "مصادقة مبنية على Better Auth.",
          "Drizzle ORM فوق Supabase لوصول بيانات مكتوب النوع.",
          "مسار تنفيذ طلبات عبر واتساب.",
        ],
      },
      results: {
        en: [
          "Live production store handling real catalog, admin, and order operations.",
          "Its architecture became the basis for the reusable Store Master Template.",
        ],
        ar: [
          "متجر إنتاجي حي يدير كتالوجًا حقيقيًا وعمليات إدارة وطلبات.",
          "أصبحت معماريته أساس قالب Store Master Template القابل لإعادة الاستخدام.",
        ],
      },
      currentStatus: {
        en: "Live and publicly deployed.",
        ar: "حي ومنشور للعامة.",
      },
    },
  },
  {
    id: "store-master-template",
    slug: "store-master-template",
    name: "Store Master Template",
    category: "Commerce",
    status: "Foundation",
    source: "GitHub README",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Sole author — extracted and generalized from ShahY Store.",
      ar: "المؤلف الوحيد — تم استخراجه وتعميمه من ShahY Store.",
    },
    description: {
      en: "Reusable e-commerce foundation extracted from ShahY Store, including storefront, admin dashboard, database, auth, storage, automation scripts, and operational docs.",
      ar: "أساس تجارة إلكترونية قابل لإعادة الاستخدام مستخرج من ShahY Store، يشمل الواجهة ولوحة الإدارة وقاعدة البيانات والمصادقة والتخزين وسكربتات الأتمتة والوثائق التشغيلية.",
    },
    impact: {
      en: "Turns one production store into a repeatable implementation system for future stores.",
      ar: "يحوّل متجرًا إنتاجيًا واحدًا إلى نظام تنفيذ قابل للتكرار لمتاجر لاحقة.",
    },
    tech: ["Next.js", "Supabase", "Drizzle ORM", "Better Auth", "PowerShell", "Docs"],
    repo: "https://github.com/Darhous/Store-Master-Template",
  },
  {
    id: "darhous-automation-academy",
    slug: "darhous-automation-academy",
    name: "Darhous Automation Academy",
    category: "Automation",
    status: "Public",
    source: "GitHub README",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Sole builder — product, content, and tooling design.",
      ar: "الباني الوحيد — تصميم المنتج والمحتوى والأدوات.",
    },
    description: {
      en: "Arabic standalone automation learning product with learning paths, templates, a workflow builder, labs, a tools hub, dashboard, and admin foundation.",
      ar: "منتج عربي مستقل لتعليم الأتمتة يضم مسارات تعليم وقوالب وباني مسارات عمل ومعامل عملية ومركز أدوات ولوحة تحكم وأساس إدارة.",
    },
    impact: {
      en: "Includes deterministic blueprint generation, ROI tools, complexity estimation, and automation service pathways.",
      ar: "يتضمن توليد مخططات حتمية وأدوات ROI وتقدير تعقيد المسارات ومسارات خدمات الأتمتة.",
    },
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "LocalStorage", "Automation Design"],
    repo: "https://github.com/Darhous/darhous-automation-academy",
  },
  {
    id: "darhous-career-hub",
    slug: "darhous-career-hub",
    name: "Darhous Career Hub — ATS Resume Analyzer",
    category: "Career",
    status: "Prototype",
    source: "GitHub README",
    year: "2025-2026",
    featured: true,
    role: {
      en: "Sole builder — product design, AI integration, and frontend/backend implementation.",
      ar: "الباني الوحيد — تصميم المنتج ودمج الذكاء الاصطناعي وتنفيذ الواجهة والخلفية.",
    },
    description: {
      en: "Career platform prototype centered on an AI-powered ATS resume analyzer, alongside interview preparation, a CV builder, templates, a jobs portal, and a dashboard.",
      ar: "نموذج منصة مهنية يتمحور حول محلل سيرة ذاتية ATS مدعوم بالذكاء الاصطناعي، إلى جانب تدريب المقابلات وصانع CV وقوالب وبوابة وظائف ولوحة تحكم.",
    },
    impact: {
      en: "The README identifies working backend features for CV upload/AI analysis (Gemini) and interview assessment; other areas run on demonstration data.",
      ar: "يوضح README أن الميزات الخلفية العاملة فعليًا تشمل رفع وتحليل السيرة بالذكاء الاصطناعي عبر Gemini وتقييم المقابلات، بينما تعمل أجزاء أخرى ببيانات تجريبية.",
    },
    tech: ["TypeScript", "Gemini AI", "Career Tools", "ATS", "Dashboard"],
    repo: "https://github.com/Darhous/Darhous-career-hub-google",
    caseStudy: {
      context: {
        en: "Job seekers rarely know why an Applicant Tracking System rejects their resume before a human ever reads it.",
        ar: "نادرًا ما يعرف الباحثون عن عمل سبب رفض نظام تتبع المتقدمين (ATS) لسيرتهم الذاتية قبل أن يقرأها إنسان أصلًا.",
      },
      problem: {
        en: "Candidates need a way to check and improve their CV against ATS logic, prepare for interviews, and manage career materials in one place.",
        ar: "يحتاج المتقدمون إلى وسيلة لفحص وتحسين سيرتهم الذاتية أمام منطق ATS، والاستعداد للمقابلات، وإدارة موادهم المهنية في مكان واحد.",
      },
      approach: {
        en: "Build an ATS Analyzer that accepts PDF/TXT resume uploads, matches them programmatically, and surfaces weaknesses through Gemini-powered analysis, alongside a STAR-method interview trainer.",
        ar: "بناء محلل ATS يستقبل رفع السيرة الذاتية بصيغة PDF أو TXT، يطابقها برمجيًا، ويكشف نقاط الضعف عبر تحليل مدعوم بـ Gemini، إلى جانب مدرب مقابلات بأسلوب STAR.",
      },
      features: {
        en: [
          "ATS Analyzer: upload and AI-assisted matching/weakness detection for PDF or TXT resumes.",
          "Interview preparation with STAR-method response crafting and Gemini assessment.",
          "CV builder for structuring resume data (export features marked in-progress).",
          "ATS-compatible resume templates (in preview).",
        ],
        ar: [
          "محلل ATS: رفع السيرة الذاتية بصيغة PDF أو TXT ومطابقتها وتحديد نقاط ضعفها بمساعدة الذكاء الاصطناعي.",
          "تدريب مقابلات بصياغة إجابات بأسلوب STAR وتقييم عبر Gemini.",
          "صانع سيرة ذاتية لهيكلة بيانات السيرة (ميزات التصدير قيد التطوير).",
          "قوالب سيرة ذاتية متوافقة مع ATS (في مرحلة معاينة).",
        ],
      },
      results: {
        en: [
          "Working end-to-end CV upload → AI analysis → weakness report flow.",
          "Functional Gemini-assessed interview evaluation module.",
        ],
        ar: [
          "مسار عامل من طرف إلى طرف: رفع السيرة ← تحليل بالذكاء الاصطناعي ← تقرير نقاط الضعف.",
          "وحدة تقييم مقابلات عاملة بتقييم Gemini.",
        ],
      },
      currentStatus: {
        en: "Prototype: the ATS analyzer and interview evaluator run on real backend logic; remaining sections (jobs portal, some templates) currently use demonstration data.",
        ar: "نموذج أولي: يعمل محلل ATS ومقيّم المقابلات بمنطق خلفي حقيقي، بينما تعمل أقسام أخرى (بوابة الوظائف وبعض القوالب) حاليًا ببيانات تجريبية.",
      },
    },
  },
  {
    id: "darhous-iot-lab",
    slug: "darhous-iot-lab",
    name: "Darhous IoT Lab",
    category: "IoT",
    status: "Public",
    source: "GitHub README",
    year: "2025-2026",
    featured: true,
    role: {
      en: "Sole builder — curriculum design, simulation content, and platform engineering.",
      ar: "الباني الوحيد — تصميم المنهج ومحتوى المحاكاة وهندسة المنصة.",
    },
    description: {
      en: "Arabic-first IoT, Arduino, robotics, and smart-home educational application with lessons, projects, components, code examples, simulations, challenges, and roadmaps.",
      ar: "تطبيق تعليمي عربي لإنترنت الأشياء وArduino والروبوتات والمنزل الذكي، يضم دروسًا ومشاريع ومكونات وأمثلة كود ومحاكيات وتحديات وخرائط طريق.",
    },
    impact: {
      en: "The V2 README documents 18 learning paths, 60+ lessons, 72 projects, 80 components, 80 code examples, and 35 simulator templates.",
      ar: "يوثق README للإصدار V2 وجود 18 مسارًا و60+ درسًا و72 مشروعًا و80 مكونًا و80 مثال كود و35 قالب محاكاة.",
    },
    tech: ["Next.js", "TypeScript", "Tailwind CSS", "Lucide", "Arduino", "IoT"],
    repo: "https://github.com/Darhous/darhous-iot-lab",
    caseStudy: {
      context: {
        en: "Hands-on IoT and electronics education in Arabic is thin compared to English-language resources, and hardware access is a barrier for many learners.",
        ar: "التعليم العملي لإنترنت الأشياء والإلكترونيات باللغة العربية محدود مقارنة بالمصادر الإنجليزية، ويشكل الوصول إلى الأجهزة عائقًا لكثير من المتعلمين.",
      },
      problem: {
        en: "Arabic-speaking learners need a structured path into IoT, Arduino, robotics, and smart-home concepts without requiring physical hardware to start.",
        ar: "يحتاج المتعلم الناطق بالعربية مسارًا منظمًا لتعلم مفاهيم إنترنت الأشياء وArduino والروبوتات والمنزل الذكي دون الحاجة لأجهزة فعلية للبدء.",
      },
      approach: {
        en: "Build a content-heavy Next.js application combining structured learning paths, real code examples, and browser-based simulator templates so learners can practice before touching hardware.",
        ar: "بناء تطبيق Next.js غني بالمحتوى يجمع بين مسارات تعليم منظمة وأمثلة كود حقيقية وقوالب محاكاة تعمل في المتصفح ليتمرن المتعلم قبل التعامل مع الأجهزة الفعلية.",
      },
      features: {
        en: [
          "18 structured learning paths across IoT, Arduino, robotics, and smart-home topics.",
          "60+ lessons paired with 72 hands-on project briefs.",
          "80 documented components and 80 runnable code examples.",
          "35 browser-based simulator templates for hardware-free practice.",
        ],
        ar: [
          "18 مسار تعليم منظم يغطي إنترنت الأشياء وArduino والروبوتات ومواضيع المنزل الذكي.",
          "أكثر من 60 درسًا مرتبطة بـ72 موجز مشروع عملي.",
          "80 مكونًا موثقًا و80 مثال كود قابل للتشغيل.",
          "35 قالب محاكاة يعمل في المتصفح للتدريب دون أجهزة فعلية.",
        ],
      },
      results: {
        en: [
          "Largest structured content volume among Ahmed's public learning products.",
          "Provides a hardware-free on-ramp into IoT for Arabic-speaking beginners.",
        ],
        ar: [
          "أكبر حجم محتوى منظم بين منتجات أحمد التعليمية العامة.",
          "يوفر بوابة تعلم لإنترنت الأشياء دون الحاجة لأجهزة فعلية للمبتدئين الناطقين بالعربية.",
        ],
      },
      currentStatus: {
        en: "Public and content-complete for its documented V2 scope.",
        ar: "عام ومكتمل المحتوى ضمن نطاقه الموثق للإصدار V2.",
      },
    },
  },
  {
    id: "guardian-nexus",
    slug: "guardian-nexus",
    name: "Guardian-Nexus",
    category: "Security",
    status: "Private",
    source: "CV",
    year: "2025-Present",
    featured: true,
    private: true,
    role: {
      en: "System architect within a government security organization (CV-sourced; implementation detail is confidential).",
      ar: "مهندس النظام داخل جهة أمنية حكومية (مصدره السيرة الذاتية؛ تفاصيل التنفيذ سرية).",
    },
    description: {
      en: "AI-integrated HR and Security ERP architecture referenced in the CV, designed for personnel tracking, threat assessment, and resource allocation for 200+ staff.",
      ar: "معمارية ERP للموارد البشرية والأمن مدعومة بالذكاء الاصطناعي ومذكورة في السيرة الذاتية، موجهة لتتبع الأفراد وتقييم التهديدات وتوزيع الموارد لأكثر من 200 فرد.",
    },
    impact: {
      en: "Represents Ahmed's bridge between public security operations, AI workflows, and practical enterprise systems.",
      ar: "يمثل نقطة وصل بين عمليات الأمن العام ومسارات الذكاء الاصطناعي والأنظمة المؤسسية العملية.",
    },
    tech: ["AI Operations", "Security ERP", "Python", "OSINT", "LLMs"],
    caseStudy: {
      context: {
        en: "As Executive Office Manager & Security Liaison, Ahmed identified that personnel tracking, threat assessment, and resource allocation for 200+ staff were running on fragmented, manual processes.",
        ar: "بصفته مدير مكتب تنفيذي ومنسق أمني، لاحظ أحمد أن تتبع الأفراد وتقييم التهديدات وتوزيع الموارد لأكثر من 200 فرد كانت تعمل عبر عمليات يدوية ومجزأة.",
      },
      problem: {
        en: "A government security organization needed a unified, AI-assisted way to coordinate HR and security intelligence for a large staff without exposing sensitive operational data publicly.",
        ar: "احتاجت جهة أمنية حكومية إلى وسيلة موحدة مدعومة بالذكاء الاصطناعي لتنسيق بيانات الموارد البشرية والذكاء الأمني لعدد كبير من الأفراد دون كشف بيانات تشغيلية حساسة للعلن.",
      },
      constraints: {
        en: "Confidential, government-context system: architecture concept and role can be shared, but implementation detail, source code, and operational data must stay private.",
        ar: "نظام في سياق حكومي وسري: يمكن مشاركة مفهوم المعمارية والدور، لكن تفاصيل التنفيذ والكود التشغيلي والبيانات يجب أن تظل خاصة.",
      },
      approach: {
        en: "Architect an ERP concept that combines HR records, security-liaison workflows, Python automation, OSINT monitoring, and LLM-assisted analysis into one coordinated system.",
        ar: "تصميم مفهوم ERP يجمع سجلات الموارد البشرية ومسارات التنسيق الأمني وأتمتة Python ومراقبة OSINT وتحليل مدعوم بنماذج اللغة الكبيرة في نظام واحد منسق.",
      },
      results: {
        en: [
          "Named and referenced directly in Ahmed's CV as an active architecture initiative.",
          "Demonstrates applied AI-operations experience beyond public GitHub projects.",
        ],
        ar: [
          "مذكور بالاسم في السيرة الذاتية لأحمد كمبادرة معمارية نشطة.",
          "يوضح خبرة تطبيقية في عمليات الذكاء الاصطناعي تتجاوز مشاريع GitHub العامة.",
        ],
      },
      currentStatus: {
        en: "Private / CV-sourced. No public repository or demo exists, and none will be fabricated here.",
        ar: "خاص ومصدره السيرة الذاتية. لا يوجد مستودع أو عرض عام، ولن يتم اختلاق أي منهما هنا.",
      },
    },
  },
  {
    id: "almasa-lab-proposal",
    slug: "almasa-lab-proposal",
    name: "Almasa Medical Laboratory — Digital Transformation Proposal",
    category: "Consulting",
    status: "Public",
    source: "GitHub README",
    year: "2026",
    featured: true,
    role: {
      en: "Sole developer — proposal architecture, interactive UI, and decision-tracking system.",
      ar: "المطور الوحيد — معمارية العرض والواجهة التفاعلية ونظام تتبع القرارات.",
    },
    description: {
      en: "An interactive, Arabic/RTL single-page proposal presenting a full digital-transformation vision for a medical laboratory: public website, patient portal, staff application, admin dashboard, and unified backend.",
      ar: "عرض تفاعلي أحادي الصفحة بالعربية واتجاه RTL يقدم رؤية تحول رقمي كاملة لمعمل طبي: موقع عام، بوابة مرضى، تطبيق للموظفين، لوحة إدارة، وخلفية موحدة.",
    },
    impact: {
      en: "Built as a decision log, not a mockup: the lab owner can review, approve, modify, defer, or exclude each proposed section, and every decision is recorded for the implementation phase.",
      ar: "بُني كسجل قرارات وليس نموذجًا شكليًا فقط: يمكن لصاحب المعمل مراجعة أو اعتماد أو تعديل أو تأجيل أو استبعاد كل قسم مقترح، ويُسجَّل كل قرار لمرحلة التنفيذ.",
    },
    tech: ["React 19", "TypeScript", "Vite", "Tailwind CSS v4", "Framer Motion"],
    repo: "https://github.com/Darhous/almasa-lab-proposal",
    caseStudy: {
      context: {
        en: "A medical laboratory client needed to evaluate a large digital-transformation scope (public site, patient portal, staff app, admin dashboard, backend) before committing budget to full implementation.",
        ar: "احتاج عميل معمل طبي إلى تقييم نطاق تحول رقمي واسع (موقع عام، بوابة مرضى، تطبيق موظفين، لوحة إدارة، خلفية) قبل الالتزام بميزانية للتنفيذ الكامل.",
      },
      problem: {
        en: "Presenting a multi-system digital transformation as a static document makes it hard for a non-technical owner to compare, prioritize, or approve pieces independently.",
        ar: "عرض تحول رقمي متعدد الأنظمة كمستند ثابت يجعل من الصعب على مالك غير تقني المقارنة أو ترتيب الأولويات أو اعتماد الأجزاء بشكل مستقل.",
      },
      approach: {
        en: "Build the proposal itself as a working interactive product: every section of the digital-transformation plan is a live, navigable part of the site with an explicit approve/modify/defer/exclude decision captured in local storage, so the artifact becomes an official decision log.",
        ar: "بناء العرض نفسه كمنتج تفاعلي عامل: كل قسم من خطة التحول الرقمي جزء حي وقابل للتصفح من الموقع، مع قرار صريح (اعتماد/تعديل/تأجيل/استبعاد) يُحفظ محليًا، بحيث يتحول العرض نفسه إلى سجل قرارات رسمي.",
      },
      features: {
        en: [
          "Section-by-section proposal covering website, patient portal, staff app, admin dashboard, and backend.",
          "Per-section decision states: approve, modify, defer, or exclude.",
          "No-backend architecture — decisions persist client-side via localStorage.",
          "Arabic-first, fully RTL interface with Framer Motion interaction detail.",
        ],
        ar: [
          "عرض قسمًا بقسم يغطي الموقع وبوابة المرضى وتطبيق الموظفين ولوحة الإدارة والخلفية.",
          "حالات قرار لكل قسم: اعتماد، تعديل، تأجيل، أو استبعاد.",
          "معمارية بلا خلفية خادم — تُحفظ القرارات في المتصفح عبر localStorage.",
          "واجهة عربية أولًا بالكامل RTL مع تفاصيل تفاعل مبنية على Framer Motion.",
        ],
      },
      results: {
        en: [
          "Turned a sales/consulting document into a functioning, deployable product built with the same stack used for production client work.",
          "Automated GitHub Pages deployment via its own GitHub Actions workflow.",
        ],
        ar: [
          "حوّل مستند مبيعات/استشارة إلى منتج عامل وقابل للنشر مبني بنفس التقنيات المستخدمة في أعمال العملاء الإنتاجية.",
          "نشر آلي على GitHub Pages عبر GitHub Actions الخاص به.",
        ],
      },
      currentStatus: {
        en: "Public and deployed as a proposal/decision-tracking tool; not the final implemented lab system.",
        ar: "عام ومنشور كأداة عرض وتتبع قرارات؛ وليس نظام المعمل النهائي المنفذ.",
      },
    },
  },
  {
    id: "shemo-studio",
    slug: "shemo-studio",
    name: "Shemo Studio",
    category: "Web",
    status: "Public",
    source: "GitHub README",
    year: "2024-2025",
    featured: false,
    role: {
      en: "Sole developer — custom WordPress theme and plugin engineering.",
      ar: "المطور الوحيد — هندسة قالب وإضافة ووردبريس مخصصين.",
    },
    description: {
      en: "A custom WordPress build for a studio brand, including a bespoke plugin (shemo-core), a child theme (shemo-child), and integration documentation.",
      ar: "بناء ووردبريس مخصص لعلامة استوديو، يضم إضافة مخصصة (shemo-core)، وقالبًا فرعيًا (shemo-child)، ووثائق تكامل.",
    },
    impact: {
      en: "35 commits of iterative theme/plugin work; no public description or live URL is currently published for this repository.",
      ar: "35 عملية إيداع (commit) من العمل التكراري على القالب والإضافة؛ لا يوجد وصف عام أو رابط حي منشور حاليًا لهذا المستودع.",
    },
    tech: ["PHP", "WordPress", "JavaScript", "HTML", "CSS"],
    repo: "https://github.com/Darhous/Shemo-Studio",
  },
  {
    id: "darhous-assessment",
    slug: "darhous-assessment",
    name: "Darhous Assessment Platform",
    category: "Assessment",
    status: "Live",
    source: "GitHub metadata",
    year: "2025",
    featured: false,
    role: {
      en: "Sole developer — full-stack build and deployment.",
      ar: "المطور الوحيد — بناء متكامل ونشر.",
    },
    description: {
      en: "A full-stack assessment application with separate frontend and backend, deployed live on Vercel.",
      ar: "تطبيق تقييم متكامل بواجهة أمامية وخلفية منفصلتين، منشور حيًا على Vercel.",
    },
    impact: {
      en: "GitHub metadata shows 30 commits and a working production deployment; no public README describes the assessment domain in detail.",
      ar: "تُظهر بيانات GitHub 30 عملية إيداع ونشرًا إنتاجيًا عاملًا؛ لا يوجد README عام يصف مجال التقييم بالتفصيل.",
    },
    tech: ["JavaScript", "Python", "CSS"],
    repo: "https://github.com/Darhous/darhous-assessment",
    live: "https://darhous-assessment.vercel.app",
  },
  {
    id: "exams-platform",
    slug: "exams-platform",
    name: "Exams Platform",
    category: "Assessment",
    status: "Public",
    source: "GitHub metadata",
    year: "2025",
    featured: false,
    role: {
      en: "Sole developer.",
      ar: "المطور الوحيد.",
    },
    description: {
      en: "A Python exam-administration and grading system with AI-assisted feedback, certificate generation, and Telegram/WhatsApp notification integrations.",
      ar: "نظام إدارة وتصحيح امتحانات مبني بـ Python مع ملاحظات مدعومة بالذكاء الاصطناعي، وإصدار شهادات، وتكامل إشعارات عبر تيليجرام وواتساب.",
    },
    impact: {
      en: "Repository structure shows Gemini-based feedback generation and multi-channel notifications; no public README documents adoption or scale.",
      ar: "يُظهر هيكل المستودع توليد ملاحظات مبني على Gemini وإشعارات متعددة القنوات؛ لا يوجد README عام يوثق حجم الاستخدام أو الانتشار.",
    },
    tech: ["Python", "Gemini AI", "Telegram API", "WhatsApp"],
    repo: "https://github.com/Darhous/Exams_Platform",
  },
  {
    id: "darhous-marketing-social-hub",
    slug: "darhous-marketing-social-hub",
    name: "Darhous Marketing & Social Hub",
    category: "Marketing",
    status: "Prototype",
    source: "GitHub README",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Sole builder — design system, information architecture, and frontend.",
      ar: "الباني الوحيد — نظام التصميم ومعمارية المعلومات والواجهة الأمامية.",
    },
    description: {
      en: "An Arabic-first marketing and social-media portal for digital professionals and agencies, covering content calendars, campaign planning, persona development, and post generation.",
      ar: "بوابة تسويق ووسائل تواصل اجتماعي عربية أولًا للمحترفين والوكالات الرقمية، تغطي تقاويم المحتوى وتخطيط الحملات وبناء الشخصيات التسويقية وتوليد المنشورات.",
    },
    impact: {
      en: "README describes a production-ready Next.js portal on a custom RTL design system with IBM Plex Sans Arabic typography.",
      ar: "يصف README بوابة Next.js جاهزة للإنتاج مبنية على نظام تصميم RTL مخصص بخط IBM Plex Sans Arabic.",
    },
    tech: ["Next.js", "TypeScript", "RTL Design System", "Tailwind CSS"],
    repo: "https://github.com/Darhous/darhous-marketing-social-hub",
  },
  {
    id: "whatsapp-auto-poster",
    slug: "whatsapp-auto-poster",
    name: "WhatsApp Auto-Poster",
    category: "Automation",
    status: "Public",
    source: "GitHub (no public README)",
    year: "2025",
    featured: false,
    role: {
      en: "Sole author.",
      ar: "المؤلف الوحيد.",
    },
    description: {
      en: "A small Python automation utility that posts messages to WhatsApp on a schedule via a GitHub Actions workflow.",
      ar: "أداة أتمتة صغيرة بلغة Python لنشر رسائل على واتساب وفق جدول زمني عبر GitHub Actions.",
    },
    impact: {
      en: "A focused, single-purpose automation script rather than a full product — representative of Ahmed's Python automation habit.",
      ar: "سكربت أتمتة مركّز أحادي الغرض وليس منتجًا كاملاً — يعكس عادة أحمد في أتمتة المهام بـ Python.",
    },
    tech: ["Python", "GitHub Actions", "WhatsApp"],
    repo: "https://github.com/Darhous/whatsapp-auto-poster",
  },
  {
    id: "elfady",
    slug: "elfady-car-trading",
    name: "Elfady Car Trading",
    category: "Automotive",
    status: "Live",
    source: "GitHub README",
    year: "2025-2026",
    featured: true,
    role: {
      en: "Sole developer — storefront, admin dashboard, dual-database architecture, testing, and deployment.",
      ar: "المطور الوحيد — واجهة المتجر، لوحة الإدارة، معمارية قاعدتي البيانات، الاختبارات، والنشر.",
    },
    description: {
      en: "A live commercial platform for El-Fady, a real car dealership in Cairo: browsing used and new vehicles (392 brands, 1,200+ models), 360° viewers, appointment booking, comparisons, favorites, and a no-code admin dashboard controlling the entire site.",
      ar: "منصة تجارية حية لمعرض الفادي، معرض سيارات حقيقي في القاهرة: تصفح سيارات مستعملة وجديدة (392 ماركة، أكثر من 1,200 موديل)، عارض 360 درجة، حجز مواعيد، مقارنات، مفضلة، ولوحة إدارة بلا كود تتحكم في الموقع بالكامل.",
    },
    impact: {
      en: "README documents 89 commits, two separate Postgres databases (Supabase for store operations, Neon for the new-car catalog), Playwright E2E tests, and a live production deployment with its own admin guide.",
      ar: "يوثق README وجود 89 عملية إيداع، وقاعدتي بيانات Postgres منفصلتين (Supabase لعمليات المتجر وNeon لكتالوج السيارات الجديدة)، واختبارات Playwright من طرف إلى طرف، ونشرًا إنتاجيًا حيًا مع دليل إدارة خاص به.",
    },
    tech: [
      "Next.js 16",
      "React 19",
      "TypeScript",
      "Supabase",
      "Neon PostgreSQL",
      "Drizzle ORM",
      "Better Auth",
      "Tailwind CSS",
      "Framer Motion",
      "Vitest",
      "Playwright",
      "GitHub Actions",
    ],
    repo: "https://github.com/darhous2023/fady",
    live: "https://fady-delta.vercel.app",
    caseStudy: {
      context: {
        en: "El-Fady is a real, operating car dealership in Cairo that needed a digital storefront its own staff could run day-to-day without a developer on call.",
        ar: "معرض الفادي معرض سيارات حقيقي وعامل في القاهرة، احتاج واجهة رقمية يستطيع فريقه تشغيلها يوميًا دون الحاجة لمطور جاهز باستمرار.",
      },
      problem: {
        en: "A car dealership needed to publish and manage a large, frequently changing new-and-used inventory (used listings plus a 392-brand, 1,200+ model new-car catalog), take bookings, and run all of it without touching code.",
        ar: "احتاج معرض سيارات إلى نشر وإدارة مخزون كبير ومتغير باستمرار (إعلانات مستعملة بالإضافة إلى كتالوج سيارات جديدة يضم 392 ماركة وأكثر من 1,200 موديل)، واستقبال حجوزات، وإدارة كل ذلك دون لمس الكود.",
      },
      constraints: {
        en: "Two very different data shapes — free-form used-car listings with photos and condition notes, versus a structured new-car catalog with brand/model/trim hierarchies — needed to coexist without one architecture compromising the other.",
        ar: "شكلان مختلفان تمامًا من البيانات — إعلانات سيارات مستعملة حرة الشكل بصور وملاحظات حالة، مقابل كتالوج سيارات جديدة منظم بتسلسل ماركة/موديل/فئة — كان يجب أن يتعايشا دون أن تُضعف إحدى المعماريتين الأخرى.",
      },
      approach: {
        en: "Split storage across two purpose-fit Postgres databases (Supabase for store operations and content, Neon for the structured new-car catalog), unify them behind one Next.js 16 App Router frontend, and build a single admin panel that edits everything — inventory, bookings, testimonials, banners, financing options, and settings — without code changes.",
        ar: "تقسيم التخزين بين قاعدتي بيانات Postgres مخصصتين (Supabase لعمليات المتجر والمحتوى، وNeon لكتالوج السيارات الجديدة المنظم)، وتوحيدهما خلف واجهة أمامية واحدة على Next.js 16 App Router، وبناء لوحة إدارة واحدة تعدّل كل شيء — المخزون، الحجوزات، الشهادات، البانرات، خيارات التمويل، والإعدادات — دون تعديل الكود.",
      },
      features: {
        en: [
          "Used-car listings with multiple images, a 360° viewer, full specs, and customer reviews.",
          "New-car catalog (392 brands, 1,200+ models) with Arabic search, comparison, and favorites.",
          "Appointment booking and tracking system.",
          "Single admin dashboard controlling inventory, bookings, testimonials, banners, financing options, and site settings — 'a single pane controlling everything without touching code,' per the project's own README.",
          "Direct WhatsApp integration and database-driven social links.",
          "Internal visitor analytics tracking.",
        ],
        ar: [
          "إعلانات سيارات مستعملة بصور متعددة وعارض 360 درجة ومواصفات كاملة وتقييمات عملاء.",
          "كتالوج سيارات جديدة (392 ماركة، أكثر من 1,200 موديل) مع بحث عربي ومقارنة ومفضلة.",
          "نظام حجز مواعيد ومتابعتها.",
          "لوحة إدارة واحدة تتحكم في المخزون والحجوزات والشهادات والبانرات وخيارات التمويل وإعدادات الموقع — بحسب توصيف README الخاص بالمشروع.",
          "تكامل مباشر مع واتساب وروابط تواصل اجتماعي من قاعدة البيانات.",
          "تتبع تحليلات زوار داخلي.",
        ],
      },
      challenges: {
        en: [
          "Keeping two separate Postgres databases (Supabase and Neon) consistent behind one unified frontend and admin experience.",
          "Building an admin surface complete enough that non-technical dealership staff never need a developer for routine catalog or content changes.",
        ],
        ar: [
          "الحفاظ على اتساق قاعدتي بيانات Postgres منفصلتين (Supabase وNeon) خلف واجهة أمامية وتجربة إدارة موحدة.",
          "بناء واجهة إدارة كاملة بما يكفي بحيث لا يحتاج فريق المعرض غير التقني لمطور في تغييرات الكتالوج أو المحتوى الروتينية.",
        ],
      },
      solutions: {
        en: [
          "Drizzle ORM as a typed data layer over both databases, keeping the frontend agnostic to which database backs which content type.",
          "Row-Level Security on sensitive tables plus a dedicated `/admin/guide` page documenting how staff operate the dashboard.",
        ],
        ar: [
          "استخدام Drizzle ORM كطبقة بيانات مكتوبة النوع فوق القاعدتين، بحيث تبقى الواجهة الأمامية غير مبالية بأي قاعدة بيانات تغذي أي نوع محتوى.",
          "أمان على مستوى الصفوف (RLS) في الجداول الحساسة، بالإضافة إلى صفحة `/admin/guide` مخصصة توثّق كيفية تشغيل الفريق للوحة الإدارة.",
        ],
      },
      results: {
        en: [
          "89 commits of sustained, production-grade development, including Vitest unit tests and Playwright end-to-end tests.",
          "Live commercial deployment serving a real dealership's actual inventory and booking flow.",
          "CI/CD via GitHub Actions to a Vercel production environment.",
        ],
        ar: [
          "89 عملية إيداع من تطوير مستمر بمستوى إنتاجي، تشمل اختبارات وحدة Vitest واختبارات Playwright من طرف إلى طرف.",
          "نشر تجاري حي يخدم مخزون معرض حقيقي ومسار حجوزاته الفعلي.",
          "تكامل ونشر مستمر عبر GitHub Actions إلى بيئة إنتاج على Vercel.",
        ],
      },
      currentStatus: {
        en: "Live in production at fady-delta.vercel.app, per the project's own README (this session could not independently re-verify the URL by direct request — the darhous2023/fady repository and its README are the primary evidence).",
        ar: "حي في الإنتاج على fady-delta.vercel.app بحسب README المشروع نفسه (لم يتمكن هذا الجلسة من إعادة التحقق المباشر من الرابط عبر طلب مباشر — يبقى مستودع darhous2023/fady وREADME الخاص به هما الدليل الأساسي).",
      },
    },
  },
  {
    id: "automotive-catalog-intelligence",
    slug: "automotive-catalog-intelligence-platform",
    name: "Automotive Catalog Intelligence Platform",
    category: "Data",
    status: "Private",
    source: "Owner-provided",
    year: "2025-2026",
    featured: false,
    private: true,
    role: {
      en: "Sole developer — scraping, ETL pipeline, and data-normalization design.",
      ar: "المطور الوحيد — تصميم الاستخلاص وخط ETL وتوحيد البيانات.",
    },
    description: {
      en: "A scraping and ETL system that collects, cleans, and links car brand, model, generation, specification, and image data from multiple sources into a normalized database that powers Elfady's new-car catalog.",
      ar: "نظام استخلاص وETL يجمع وينظّف ويربط بيانات ماركات السيارات والموديلات والأجيال والمواصفات والصور من مصادر متعددة في قاعدة بيانات موحدة تغذي كتالوج السيارات الجديدة في Elfady.",
    },
    impact: {
      en: "Described by Ahmed as the data backbone behind Elfady's new-car catalog (392 brands, 1,200+ models). This is a local project without a public GitHub repository, so this description reflects the owner's own account rather than independently reviewed code.",
      ar: "وصفه أحمد بأنه العمود الفقري للبيانات خلف كتالوج السيارات الجديدة في Elfady (392 ماركة، أكثر من 1,200 موديل). هذا مشروع محلي بلا مستودع GitHub عام، لذلك يعكس هذا الوصف رواية صاحب المشروع وليس مراجعة مستقلة للكود.",
    },
    tech: ["Node.js", "TypeScript", "Prisma", "PostgreSQL", "Neon", "Web Scraping", "ETL"],
  },
  {
    id: "elfady-android",
    slug: "elfady-native-android-app",
    name: "Elfady Native Android App",
    category: "Mobile",
    status: "Early",
    source: "GitHub (no public README)",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Owner-listed repository; no public implementation to describe yet.",
      ar: "مستودع مسجل باسم أحمد؛ لا يوجد تنفيذ عام لوصفه بعد.",
    },
    description: {
      en: "A repository reserved for a native Flutter/Android companion app to the Elfady platform. The repository is public but currently empty, so no verified feature set, screenshots, or build can be shown yet.",
      ar: "مستودع محجوز لتطبيق Flutter/Android مصاحب لمنصة Elfady. المستودع عام حاليًا لكنه فارغ، لذلك لا يمكن عرض مزايا أو لقطات شاشة أو نسخة تشغيل موثقة بعد.",
    },
    impact: {
      en: "Listed here for transparency, not as a completed case study — this entry will be expanded once real code or a build is published.",
      ar: "مُدرَج هنا للشفافية وليس كدراسة حالة مكتملة — سيتم توسيع هذا العنصر عند نشر كود أو نسخة تشغيل حقيقية.",
    },
    tech: ["Flutter", "Dart"],
    repo: "https://github.com/darhous2023/flutter_test",
  },
  {
    id: "nexalearn-ai-academy",
    slug: "nexalearn-ai-academy",
    name: "NexaLearn AI Academy",
    category: "Learning",
    status: "Live",
    source: "GitHub README",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Sole builder — part of the NexaLearn platform.",
      ar: "الباني الوحيد — جزء من منصة NexaLearn.",
    },
    description: {
      en: "One of NexaLearn's seven portals: structured courses and learning paths for AI, machine learning, deep learning, generative AI, and Claude-focused prompt engineering, with applied labs and project-based challenges.",
      ar: "إحدى بوابات NexaLearn السبع: دورات ومسارات تعليم منظمة للذكاء الاصطناعي والتعلم الآلي والتعلم العميق والذكاء الاصطناعي التوليدي وهندسة الأوامر المرتكزة على Claude، مع معامل تطبيقية وتحديات قائمة على مشاريع.",
    },
    impact: {
      en: "The NexaLearn README documents this portal at route `/{locale}/ai-academy` with AI courses, applied labs, project challenges, and AI mentor support.",
      ar: "يوثق README الخاص بـ NexaLearn هذه البوابة على المسار `/{locale}/ai-academy` بدورات ذكاء اصطناعي ومعامل تطبيقية وتحديات مشاريع ودعم من AI Mentor.",
    },
    tech: ["Next.js", "React", "TypeScript", "Supabase", "MDX", "Gemini AI"],
    repo: "https://github.com/Darhous/darhous-ai-cloud-academy",
    live: "https://darhous-ai-cloud-academy.vercel.app/en/ai-academy",
  },
  {
    id: "nexalearn-language-assessment",
    slug: "english-language-assessment-platform",
    name: "English Language Assessment Platform",
    category: "Assessment",
    status: "Live",
    source: "GitHub README",
    year: "2025-2026",
    featured: true,
    role: {
      en: "Sole builder — part of the NexaLearn platform.",
      ar: "الباني الوحيد — جزء من منصة NexaLearn.",
    },
    description: {
      en: "An adaptive English-proficiency assessment portal within NexaLearn: instant skill scoring, learning-history tracking, and personalized recommendations based on the learner's result.",
      ar: "بوابة تقييم كفاءة إنجليزية تكيفية ضمن NexaLearn: تسجيل نتائج فوري، تتبع لتاريخ التعلم، وتوصيات مخصصة بناءً على نتيجة المتعلم.",
    },
    impact: {
      en: "Documented in the NexaLearn README at route `/{locale}/language` as English proficiency assessment with instant scoring and personalized recommendations. Ahmed additionally describes it as a 10-stage, 150-question adaptive test with certificate output — that scale detail is owner-provided and not independently confirmed against the public README.",
      ar: "موثقة في README الخاص بـ NexaLearn على المسار `/{locale}/language` كتقييم كفاءة إنجليزية بتسجيل فوري وتوصيات مخصصة. يصفها أحمد إضافيًا بأنها اختبار تكيفي من 10 مراحل و150 سؤالًا مع إصدار شهادة — هذا التفصيل مصدره صاحب المشروع ولم يُؤكَّد بشكل مستقل من README العام.",
    },
    tech: ["Next.js", "React", "TypeScript", "Supabase", "Adaptive Testing", "React PDF"],
    repo: "https://github.com/Darhous/darhous-ai-cloud-academy",
    live: "https://darhous-ai-cloud-academy.vercel.app/en/language",
  },
  {
    id: "nexalearn-digital-exams",
    slug: "digital-transformation-exams-platform",
    name: "Digital Transformation Exams Platform",
    category: "Assessment",
    status: "Live",
    source: "GitHub README",
    year: "2025-2026",
    featured: true,
    role: {
      en: "Sole builder — part of the NexaLearn platform.",
      ar: "الباني الوحيد — جزء من منصة NexaLearn.",
    },
    description: {
      en: "A digital-skills exam portal within NexaLearn covering IT certifications, Microsoft Office skill validation, cybersecurity assessments, and digital-transformation competency testing.",
      ar: "بوابة اختبارات مهارات رقمية ضمن NexaLearn تغطي شهادات تقنية المعلومات والتحقق من مهارات Microsoft Office وتقييمات الأمن السيبراني واختبارات كفاءة التحول الرقمي.",
    },
    impact: {
      en: "Documented in the NexaLearn README at route `/{locale}/digital-exams`. Ahmed additionally describes a bank of 900+ questions across IT, Word, Excel, PowerPoint, Access, mobile, web, cybersecurity, and internet research — that question count is owner-provided and not independently counted from the public README.",
      ar: "موثقة في README الخاص بـ NexaLearn على المسار `/{locale}/digital-exams`. يصفها أحمد إضافيًا ببنك يضم أكثر من 900 سؤال في تقنية المعلومات وWord وExcel وPowerPoint وAccess والموبايل والويب والأمن السيبراني والبحث على الإنترنت — هذا العدد مصدره صاحب المشروع ولم يُحصَ بشكل مستقل من README العام.",
    },
    tech: ["Next.js", "React", "TypeScript", "Supabase", "Randomized Exams", "React PDF"],
    repo: "https://github.com/Darhous/darhous-ai-cloud-academy",
    live: "https://darhous-ai-cloud-academy.vercel.app/en/digital-exams",
  },
  {
    id: "nexalearn-career-hub",
    slug: "nexalearn-career-hub",
    name: "NexaLearn Career Hub",
    category: "Career",
    status: "Live",
    source: "GitHub README",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Sole builder — part of the NexaLearn platform.",
      ar: "الباني الوحيد — جزء من منصة NexaLearn.",
    },
    description: {
      en: "NexaLearn's built-in career portal: AI-powered CV analysis, ATS scoring, CV building, job-opportunity matching, and interview preparation — distinct from the standalone 'Darhous Career Hub' prototype elsewhere in this archive.",
      ar: "بوابة التوظيف المدمجة في NexaLearn: تحليل سيرة ذاتية بالذكاء الاصطناعي، تسجيل ATS، بناء سيرة ذاتية، مطابقة فرص عمل، وتحضير للمقابلات — وهي مختلفة عن نموذج 'Darhous Career Hub' المستقل الموجود في مكان آخر من هذا الأرشيف.",
    },
    impact: {
      en: "Documented in the NexaLearn README at route `/{locale}/career`.",
      ar: "موثقة في README الخاص بـ NexaLearn على المسار `/{locale}/career`.",
    },
    tech: ["Next.js", "React", "TypeScript", "Supabase", "Gemini AI", "PDF Parsing"],
    repo: "https://github.com/Darhous/darhous-ai-cloud-academy",
    live: "https://darhous-ai-cloud-academy.vercel.app/en/career",
  },
  {
    id: "nexalearn-automation-academy",
    slug: "nexalearn-automation-academy",
    name: "NexaLearn Automation Academy",
    category: "Automation",
    status: "Live",
    source: "GitHub README",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Sole builder — part of the NexaLearn platform.",
      ar: "الباني الوحيد — جزء من منصة NexaLearn.",
    },
    description: {
      en: "A business-automation learning portal within NexaLearn: curated workflow recipes, practical labs, and template-based guidance — distinct from the standalone 'Darhous Automation Academy' product elsewhere in this archive.",
      ar: "بوابة تعلم أتمتة الأعمال ضمن NexaLearn: وصفات مسارات عمل منتقاة، معامل عملية، وإرشاد قائم على قوالب — وهي مختلفة عن منتج 'Darhous Automation Academy' المستقل الموجود في مكان آخر من هذا الأرشيف.",
    },
    impact: {
      en: "Documented in the NexaLearn README at route `/{locale}/automation`.",
      ar: "موثقة في README الخاص بـ NexaLearn على المسار `/{locale}/automation`.",
    },
    tech: ["Next.js", "React", "TypeScript", "Supabase", "Automation Design"],
    repo: "https://github.com/Darhous/darhous-ai-cloud-academy",
    live: "https://darhous-ai-cloud-academy.vercel.app/en/automation",
  },
  {
    id: "nexalearn-iot-lab",
    slug: "nexalearn-iot-lab",
    name: "NexaLearn IoT Lab / Arduinoverse",
    category: "IoT",
    status: "Live",
    source: "GitHub README",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Sole builder — part of the NexaLearn platform.",
      ar: "الباني الوحيد — جزء من منصة NexaLearn.",
    },
    description: {
      en: "An Arduino and IoT learning portal within NexaLearn: lessons, applied projects, programming challenges, component references, and simulator-based learning — distinct from the standalone 'Darhous IoT Lab' product elsewhere in this archive.",
      ar: "بوابة تعلم Arduino وإنترنت الأشياء ضمن NexaLearn: دروس ومشاريع تطبيقية وتحديات برمجية ومراجع مكونات وتعلم قائم على محاكاة — وهي مختلفة عن منتج 'Darhous IoT Lab' المستقل الموجود في مكان آخر من هذا الأرشيف.",
    },
    impact: {
      en: "Documented in the NexaLearn README at route `/{locale}/iot-lab`.",
      ar: "موثقة في README الخاص بـ NexaLearn على المسار `/{locale}/iot-lab`.",
    },
    tech: ["Next.js", "React", "TypeScript", "Arduino", "IoT", "Interactive Simulation"],
    repo: "https://github.com/Darhous/darhous-ai-cloud-academy",
    live: "https://darhous-ai-cloud-academy.vercel.app/en/iot-lab",
  },
  {
    id: "nano-banana-prompt-lab",
    slug: "nano-banana-prompt-lab",
    name: "Nano Banana Prompt Lab",
    category: "AI Tools",
    status: "Live",
    source: "Owner-provided",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Sole builder — part of the NexaLearn platform.",
      ar: "الباني الوحيد — جزء من منصة NexaLearn.",
    },
    description: {
      en: "A specialized lab within NexaLearn for creating, testing, and refining prompts for image generation and editing with Gemini's 'Nano Banana' image model.",
      ar: "معمل متخصص ضمن NexaLearn لإنشاء وتجربة وتحسين برومبتات توليد وتعديل الصور باستخدام نموذج الصور 'Nano Banana' من Gemini.",
    },
    impact: {
      en: "Route and description as provided by Ahmed; the NexaLearn README fetched for this archive documents the platform's other six portals and eight AI Studio tools explicitly but did not separately list this route by name, so it is marked owner-provided rather than README-confirmed.",
      ar: "المسار والوصف كما قدمهما أحمد؛ يوثق README الخاص بـ NexaLearn الذي تم فحصه لهذا الأرشيف البوابات الست الأخرى وأدوات AI Studio الثمانية بشكل صريح، لكنه لم يُدرج هذا المسار تحديدًا بالاسم، لذلك صُنِّف كمعلومة من صاحب المشروع وليست مؤكدة من README.",
    },
    tech: ["Next.js", "React", "TypeScript", "Gemini API", "Prompt Engineering"],
    repo: "https://github.com/Darhous/darhous-ai-cloud-academy",
    live: "https://darhous-ai-cloud-academy.vercel.app/en/nano-banana-prompts",
  },
  {
    id: "ai-mentor",
    slug: "ai-mentor",
    name: "AI Mentor",
    category: "AI Tools",
    status: "Live",
    source: "GitHub README",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Sole builder — one of eight AI Studio tools inside NexaLearn.",
      ar: "الباني الوحيد — إحدى أدوات AI Studio الثمانية داخل NexaLearn.",
    },
    description: {
      en: "A context-aware AI guide inside NexaLearn that answers learner questions and provides support across every course and portal.",
      ar: "مرشد ذكاء اصطناعي واعٍ للسياق داخل NexaLearn يجيب عن أسئلة المتعلم ويقدم الدعم عبر كل دورة وبوابة.",
    },
    impact: {
      en: "Documented in the NexaLearn README as providing 'context-aware academy guidance and learning support' at route `/{locale}/mentor`. Selected by Ahmed as one of the three strongest AI Studio tools to feature independently.",
      ar: "موثق في README الخاص بـ NexaLearn بأنه يقدم 'إرشادًا واعيًا للسياق ودعمًا تعليميًا' على المسار `/{locale}/mentor`. اختاره أحمد كواحد من أقوى ثلاث أدوات ضمن AI Studio لعرضها بشكل مستقل.",
    },
    tech: ["Next.js", "TypeScript", "Gemini API", "Supabase"],
    repo: "https://github.com/Darhous/darhous-ai-cloud-academy",
    live: "https://darhous-ai-cloud-academy.vercel.app/en/mentor",
  },
  {
    id: "prompt-studio",
    slug: "prompt-studio",
    name: "Prompt Studio",
    category: "AI Tools",
    status: "Live",
    source: "GitHub README",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Sole builder — one of eight AI Studio tools inside NexaLearn.",
      ar: "الباني الوحيد — إحدى أدوات AI Studio الثمانية داخل NexaLearn.",
    },
    description: {
      en: "A tool inside NexaLearn's AI Studio for building, structuring, and improving prompts to get stronger, more reliable outputs from AI models.",
      ar: "أداة داخل AI Studio في NexaLearn لبناء وهيكلة وتحسين البرومبتات للحصول على مخرجات أقوى وأكثر موثوقية من نماذج الذكاء الاصطناعي.",
    },
    impact: {
      en: "Documented in the NexaLearn README as enabling learners to 'improve and structure prompts for stronger outputs' at route `/{locale}/prompt-studio`. Selected by Ahmed as one of the three strongest AI Studio tools to feature independently.",
      ar: "موثقة في README الخاص بـ NexaLearn بأنها تمكّن المتعلم من 'تحسين وهيكلة البرومبتات للحصول على مخرجات أقوى' على المسار `/{locale}/prompt-studio`. اختارها أحمد كواحدة من أقوى ثلاث أدوات ضمن AI Studio لعرضها بشكل مستقل.",
    },
    tech: ["Next.js", "TypeScript", "Gemini API", "Prompt Engineering"],
    repo: "https://github.com/Darhous/darhous-ai-cloud-academy",
    live: "https://darhous-ai-cloud-academy.vercel.app/en/prompt-studio",
  },
  {
    id: "claude-code-prompt-generator",
    slug: "claude-code-prompt-generator",
    name: "Claude Code Prompt Generator",
    category: "AI Tools",
    status: "Live",
    source: "GitHub README",
    year: "2025-2026",
    featured: false,
    role: {
      en: "Sole builder — one of eight AI Studio tools inside NexaLearn.",
      ar: "الباني الوحيد — إحدى أدوات AI Studio الثمانية داخل NexaLearn.",
    },
    description: {
      en: "A tool inside NexaLearn's AI Studio that builds detailed, executable implementation prompts for use with Claude Code when developing or reviewing software projects.",
      ar: "أداة داخل AI Studio في NexaLearn تبني برومبتات تنفيذية مفصلة للاستخدام مع Claude Code عند تطوير أو مراجعة مشاريع برمجية.",
    },
    impact: {
      en: "Documented in the NexaLearn README as helping learners 'build detailed implementation prompts for coding workflows' at route `/{locale}/claude-code-generator`. Selected by Ahmed as one of the three strongest AI Studio tools to feature independently.",
      ar: "موثقة في README الخاص بـ NexaLearn بأنها تساعد المتعلم على 'بناء برومبتات تنفيذية مفصلة لمسارات البرمجة' على المسار `/{locale}/claude-code-generator`. اختارها أحمد كواحدة من أقوى ثلاث أدوات ضمن AI Studio لعرضها بشكل مستقل.",
    },
    tech: ["Next.js", "TypeScript", "AI APIs", "Prompt Engineering"],
    repo: "https://github.com/Darhous/darhous-ai-cloud-academy",
    live: "https://darhous-ai-cloud-academy.vercel.app/en/claude-code-generator",
  },
  {
    id: "nutribox-healthy-kitchen-os",
    slug: "nutribox-healthy-kitchen-os",
    name: "NutriBox Healthy Kitchen OS",
    category: "Hospitality",
    status: "Private",
    source: "Owner-provided",
    year: "2025-2026",
    featured: false,
    private: true,
    role: {
      en: "Sole developer — full system design across every operational role.",
      ar: "المطور الوحيد — تصميم النظام الكامل عبر كل الأدوار التشغيلية.",
    },
    description: {
      en: "A complete operating system for a healthy-food and meal-prep restaurant: customer ordering, management, cashier, kitchen, delivery, subscriptions, inventory, and nutrition tracking in one connected system.",
      ar: "نظام تشغيل متكامل لمطعم أكل صحي وMeal Prep: طلب العملاء، الإدارة، الكاشير، المطبخ، التوصيل، الاشتراكات، المخزون، وتتبع التغذية في نظام واحد مترابط.",
    },
    impact: {
      en: "Described by Ahmed as a multi-role restaurant OS. No public GitHub repository was found under either known account (`Darhous`, `darhous2023`) during this session's discovery, so this entry reflects the owner's own description rather than independently reviewed code, screenshots, or a live link.",
      ar: "وصفه أحمد بأنه نظام تشغيل مطعم متعدد الأدوار. لم يُعثر على مستودع GitHub عام تحت أي من الحسابين المعروفين (`Darhous`، `darhous2023`) أثناء بحث هذه الجلسة، لذلك يعكس هذا العنصر وصف صاحب المشروع نفسه وليس مراجعة مستقلة للكود أو لقطات شاشة أو رابط حي.",
    },
    tech: ["React", "TypeScript", "Vite", "Tailwind CSS", "Framer Motion"],
  },
  {
    id: "fenrir-cybersecurity",
    slug: "fenrir-cybersecurity-projects",
    name: "Fenrir Cybersecurity Projects",
    category: "Security",
    status: "Private",
    source: "Owner-provided",
    year: "2025-2026",
    featured: false,
    private: true,
    role: {
      en: "Sole researcher — fuzzing harness design and memory-safety research.",
      ar: "الباحث الوحيد — تصميم أطر Fuzzing وأبحاث سلامة الذاكرة.",
    },
    description: {
      en: "A set of fuzzing and security-research repositories aimed at discovering memory-safety bugs such as use-after-free, heap buffer overflow, and double-free defects.",
      ar: "مجموعة مستودعات فحص عشوائي (Fuzzing) وأبحاث أمنية تهدف لاكتشاف أخطاء سلامة الذاكرة مثل Use-After-Free وHeap Buffer Overflow وDouble Free.",
    },
    impact: {
      en: "Described by Ahmed with a specific toolchain (C, C++, Rust, Java/JVM, LLVM/Clang, AddressSanitizer, libFuzzer, ClusterFuzzLite). No repository matching 'Fenrir' was found under the `Darhous` or `darhous2023` GitHub accounts during this session's discovery; Ahmed's message indicates the work may live under a different GitHub account not yet provided. This entry is listed for transparency and should be expanded with a repository link once one is available.",
      ar: "وصفه أحمد بمجموعة أدوات محددة (C وC++ وRust وJava/JVM وLLVM/Clang وAddressSanitizer وlibFuzzer وClusterFuzzLite). لم يُعثر على مستودع باسم 'Fenrir' تحت حسابي `Darhous` أو `darhous2023` أثناء بحث هذه الجلسة؛ تشير رسالة أحمد إلى أن العمل قد يكون تحت حساب GitHub مختلف لم يُقدَّم بعد. هذا العنصر مُدرَج للشفافية ويجب توسيعه برابط مستودع عند توفره.",
    },
    tech: [
      "C",
      "C++",
      "Rust",
      "Java",
      "JVM",
      "LLVM",
      "Clang",
      "AddressSanitizer",
      "libFuzzer",
      "ClusterFuzzLite",
    ],
  },
  {
    id: "portfolio",
    slug: "ahmed-darhous-portfolio",
    name: "Ahmed Darhous Portfolio",
    category: "Portfolio",
    status: "Live",
    source: "GitHub metadata",
    year: "2026",
    featured: false,
    role: {
      en: "Sole designer and developer.",
      ar: "المصمم والمطور الوحيد.",
    },
    description: {
      en: "This bilingual portfolio itself: a GitHub Pages-compatible Vite + React application with centralized identity, a real project archive, and case-study pages.",
      ar: "هذا البورتفوليو الثنائي اللغة نفسه: تطبيق Vite وReact متوافق مع GitHub Pages بهوية مركزية وأرشيف مشاريع حقيقي وصفحات دراسات حالة.",
    },
    impact: {
      en: "Acts as the public identity system tying together security, legal research, AI operations, and software products.",
      ar: "يمثل نظام الهوية العام الذي يربط الأمن والبحث القانوني وعمليات الذكاء الاصطناعي والمنتجات البرمجية.",
    },
    tech: ["Vite", "React", "TypeScript", "React Router", "GitHub Pages"],
    repo: "https://github.com/Darhous/portofolio",
    live: "https://darhous.github.io/portofolio/",
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((project) => project.slug === slug);
}

export const featuredProjects = projects.filter((project) => project.featured);

export const projectCategories = Array.from(new Set(projects.map((project) => project.category)));
